<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\APIGateway\HMIS.Aggregator.API\HMIS.Aggregator.API.csproj" />
    <ProjectReference Include="..\..\..\ApplicationCore\Common\AppCommonMethods\AppCommonMethods.csproj" />
    <ProjectReference Include="..\..\..\ApplicationCore\Common\FileHandler\FileHandler.csproj" />
    <ProjectReference Include="..\..\..\ApplicationCore\Common\JWTAuthentication\JWTAuthentication.csproj" />
    <ProjectReference Include="..\..\..\ApplicationCore\Common\SMSSender\SMSSender.csproj" />
    <ProjectReference Include="..\HMIS.NCD.Domain\HMIS.NCD.Domain.csproj" />
  </ItemGroup>

</Project>
