<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\ApplicationCore\Common\AppCommonMethods\AppCommonMethods.csproj" />
    <ProjectReference Include="..\..\ApplicationCore\Common\CommonExceptionHandler\CommonExceptionHandler.csproj" />
    <ProjectReference Include="..\..\ApplicationCore\Common\JWTAuthentication\JWTAuthentication.csproj" />
    <ProjectReference Include="..\..\Services\MIMS\HMIS.MIMS.Domain\HMIS.MIMS.Domain.csproj" />
  </ItemGroup>

</Project>
