<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="7.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="7.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\ApplicationCore\Common\CommonMessages\CommonMessages.csproj" />
    <ProjectReference Include="..\..\..\ApplicationCore\HMIS.ApplicationCore.Common\HMIS.ApplicationCore.Common.csproj" />
    <ProjectReference Include="..\..\Auth\DAL\AuthDAL\AuthDAL.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Models\DTO\Common\" />
    <Folder Include="Models\DTO\PatientDto\" />
  </ItemGroup>

</Project>
