using System;
using System.Collections.Generic;

namespace HMIS.DrugAddict.Domain.Models.DbModels;

public partial class SscVisitStatusLog
{
    public Guid PatientOpenVisitId { get; set; }

    public Guid? ParentPatientOpenVisitId { get; set; }

    public string? SlipNo { get; set; }

    public string? TokenNo { get; set; }

    public int? VisitNo { get; set; }

    public Guid? PatientId { get; set; }

    public int? HealthFacilityId { get; set; }

    public int? DepartementLookupId { get; set; }

    public int? SectionLookupId { get; set; }

    public DateTime? VisitDate { get; set; }

    public bool IsFromPmis { get; set; }

    public bool? IsDischarge { get; set; }

    public bool? IsVisitExternally { get; set; }

    public bool? IsAdmittedInIpd { get; set; }

    public bool? IsAutoGenerated { get; set; }

    public bool? IsFromCallCenter { get; set; }

    public int? SscStatus { get; set; }

    public string? SscStatusReason { get; set; }

    public DateTime? SscStatusUpdatedOn { get; set; }

    public Guid? SscStatusUpdatedBy { get; set; }

    public string? SscNumber { get; set; }

    public bool IsActive { get; set; }

    public DateTime? CreatedOn { get; set; }

    public Guid? CreatedBy { get; set; }

    public DateTime? UpdatedOn { get; set; }

    public Guid? UpdatedBy { get; set; }

    public DateTime? DeletedOn { get; set; }

    public Guid? DeletedBy { get; set; }

    public byte ActionTypeId { get; set; }

    public DateTime ActionDate { get; set; }
}
