//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRReports.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditLog
    {
        public long AuditLogId { get; set; }
        public string PathAndQuery { get; set; }
        public string RequestURL { get; set; }
        public string LocalPath { get; set; }
        public string Method { get; set; }
        public Nullable<int> Port { get; set; }
        public string JsonBody { get; set; }
        public bool IsModelStateValid { get; set; }
        public string ModelStateError { get; set; }
        public string Token { get; set; }
        public string Host { get; set; }
        public string HostNameType { get; set; }
        public string IdnHost { get; set; }
        public Nullable<System.DateTime> RequestTime { get; set; }
        public Nullable<System.DateTime> ResponseTime { get; set; }
        public string ResponseData { get; set; }
        public bool IsError { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.Guid> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<long> UserLogId { get; set; }
        public byte ActionTypeId { get; set; }
    }
}
