//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRReports.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BirthCertificate
    {
        public System.Guid BirthCertificateId { get; set; }
        public Nullable<System.Guid> PatientId { get; set; }
        public Nullable<System.Guid> PatientVisitId { get; set; }
        public Nullable<System.Guid> PatientDiagnoseId { get; set; }
        public Nullable<int> HealthFacilityId { get; set; }
        public Nullable<System.Guid> DoctorId { get; set; }
        public Nullable<System.Guid> EntryStatusProfileId { get; set; }
        public string TrackingId { get; set; }
        public string CrmsNo { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public string Address { get; set; }
        public string MotherName { get; set; }
        public string MotherCnic { get; set; }
        public string FatherName { get; set; }
        public string FatherCnic { get; set; }
        public string QrCodeImagePath { get; set; }
        public Nullable<System.Guid> OccupationTypeProfileId { get; set; }
        public Nullable<System.Guid> FatherNationalityTypeProfileId { get; set; }
        public Nullable<System.Guid> MotherNationalityTypeProfileId { get; set; }
        public Nullable<System.Guid> ReligiousProfileId { get; set; }
        public string GrandFatherName { get; set; }
        public string GrandFatherCnic { get; set; }
        public string ChildName { get; set; }
        public Nullable<System.Guid> GenderProfileId { get; set; }
        public Nullable<System.Guid> ChildBloodGroupProfileId { get; set; }
        public Nullable<System.Guid> MotherBloodGroupProfileId { get; set; }
        public Nullable<int> DistrictOfBirthId { get; set; }
        public Nullable<int> DistrictId { get; set; }
        public Nullable<int> AnnualNumber { get; set; }
        public Nullable<int> TehsilId { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string PlaceOfBirth { get; set; }
        public string GynaeUnit { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<System.Guid> UpdatedBy { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public Nullable<System.Guid> DeletedBy { get; set; }
        public byte ActionTypeId { get; set; }
    }
}
