//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRReports.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataSyncUtilityLog
    {
        public System.Guid DataSyncUtilityLogId { get; set; }
        public int HealthFacilityId { get; set; }
        public string FileName { get; set; }
        public int Status { get; set; }
        public System.DateTime StatusUpdatedOn { get; set; }
        public Nullable<System.DateTime> UploadedOn { get; set; }
        public Nullable<System.DateTime> ProcessedOn { get; set; }
        public Nullable<System.DateTime> CompletedOn { get; set; }
        public string Message { get; set; }
        public string ServerType { get; set; }
        public string FileSize { get; set; }
        public Nullable<int> FileStatus { get; set; }
    }
}
