//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRReports.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataSyncPatientRecord
    {
        public int DataSyncPatientRecordId { get; set; }
        public Nullable<System.Guid> OldPatientId { get; set; }
        public Nullable<System.Guid> NewPatientId { get; set; }
        public Nullable<int> HealthFacilityId { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<byte> ActionTypeId { get; set; }
    }
}
