//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRReports.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataSyncToOffline
    {
        public long DataSyncToOfflineId { get; set; }
        public string TableName { get; set; }
        public int HealthFacilityId { get; set; }
        public Nullable<System.DateTime> SyncOn { get; set; }
        public Nullable<System.DateTime> PrevSyncOn { get; set; }
        public byte ActionTypeId { get; set; }
        public System.DateTime ActionOn { get; set; }
        public string Type { get; set; }
        public string Status { get; set; }
        public string WorkFlow { get; set; }
        public string Json { get; set; }
    }
}
