//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRReports.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeadBodiesListView
    {
        public System.Guid UnknownPatientId { get; set; }
        public string TransactionId { get; set; }
        public string Message { get; set; }
        public string MRNo { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string FullName { get; set; }
        public string CNIC { get; set; }
        public string MobileNo { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<System.Guid> GenderProfileId { get; set; }
        public Nullable<int> ProvinceId { get; set; }
        public Nullable<int> HealthFacilityId { get; set; }
        public Nullable<bool> IsPendingVerification { get; set; }
        public Nullable<System.DateTime> TransctionSaveTime { get; set; }
        public Nullable<bool> IsTransactionSaveSuccessfully { get; set; }
        public byte ActionTypeId { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
    }
}
