//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRReports.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileUploadedToMasterServerLog
    {
        public System.Guid FileUploadedToMasterServerLogId { get; set; }
        public string FileName { get; set; }
        public Nullable<int> HealthFacilityId { get; set; }
        public Nullable<System.DateTime> UploadedDateTime { get; set; }
        public Nullable<bool> IsProcessed { get; set; }
        public Nullable<System.DateTime> ProcessOn { get; set; }
        public string CdnUrl { get; set; }
    }
}
