//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRReports.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class GetAdditionalInfo
    {
        public System.Guid PatientAdditionalInfoId { get; set; }
        public Nullable<System.Guid> PatientId { get; set; }
        public System.Guid PatientOpenVisitId { get; set; }
        public Nullable<int> HealthFacilityId { get; set; }
        public string GuardianName { get; set; }
        public string GuardianAddress { get; set; }
        public string GuardianCNIC { get; set; }
        public string GuardianMobileNo { get; set; }
        public string Caste { get; set; }
        public string Occupation { get; set; }
        public string MleIncidentPlace { get; set; }
        public Nullable<System.Guid> CaseTypeProfileId { get; set; }
        public Nullable<System.Guid> MlcSvCaseTypeProfileId { get; set; }
        public Nullable<System.Guid> DoctorId { get; set; }
        public string MLCNo { get; set; }
        public Nullable<System.Guid> MLCTypeProfileId { get; set; }
        public string PmeIncidentPlace { get; set; }
        public string MlcSvIncidentPlace { get; set; }
        public string PoliceDistrict { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string PoliceDocketOne { get; set; }
        public string PoliceDocketTwo { get; set; }
        public string PoliceDocketThree { get; set; }
        public string CaseAgainst { get; set; }
        public string MlcType { get; set; }
    }
}
