//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRReports.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class GetAllPatientThatAreNotCheckedYet
    {
        public System.Guid PatientId { get; set; }
        public System.Guid PatientVisitId { get; set; }
        public Nullable<System.Guid> PatientDiagnoseId { get; set; }
        public Nullable<int> HealthFacilityId { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string PatientName { get; set; }
        public string Relation { get; set; }
        public string DoctorName { get; set; }
        public string CNIC { get; set; }
        public string ShortName { get; set; }
    }
}
