//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRReports.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class GetALLMenuForSuperAdmin
    {
        public System.Guid MenuId { get; set; }
        public Nullable<System.Guid> ModuleId { get; set; }
        public string Name { get; set; }
        public string DisplayName { get; set; }
        public string URL { get; set; }
        public string Icon { get; set; }
        public Nullable<int> SeqNo { get; set; }
        public Nullable<System.Guid> ParentId { get; set; }
        public Nullable<bool> IsAPI { get; set; }
        public Nullable<bool> IsLabel { get; set; }
        public Nullable<bool> IsModule { get; set; }
        public bool IsDisplayMenu { get; set; }
        public bool IsActive { get; set; }
        public string ImageURL { get; set; }
        public int CanDelete { get; set; }
        public int CanEdit { get; set; }
        public int CanRead { get; set; }
        public int CanWrite { get; set; }
    }
}
