//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRReports.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class GetAllMlcQueData
    {
        public System.Guid PatientId { get; set; }
        public System.Guid PatientVisitId { get; set; }
        public string TokenNo { get; set; }
        public string MRNo { get; set; }
        public string CNIC { get; set; }
        public string MobileNo { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string FullName { get; set; }
        public int DepartmentLookupId { get; set; }
        public string DepartmentName { get; set; }
        public Nullable<int> SectionLookupId { get; set; }
        public string SectionName { get; set; }
        public string PatientCondition { get; set; }
        public Nullable<int> BedNo { get; set; }
        public string VisitFor { get; set; }
        public Nullable<System.DateTime> VisitDate { get; set; }
        public Nullable<System.Guid> DoctorId { get; set; }
        public Nullable<int> HealthFacilityId { get; set; }
        public Nullable<long> rn { get; set; }
    }
}
