//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRReports.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class HealthFacility
    {
        public int HealthFacilityId { get; set; }
        public Nullable<int> HrId { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public string HealthFacilityTypeCode { get; set; }
        public Nullable<int> HealthFacilityTypeId { get; set; }
        public Nullable<int> ProvinceId { get; set; }
        public string ProvinceCode { get; set; }
        public Nullable<int> DivisionId { get; set; }
        public string DivisionCode { get; set; }
        public Nullable<int> DistrictId { get; set; }
        public string DistrictCode { get; set; }
        public Nullable<int> TehsilId { get; set; }
        public string TehsilCode { get; set; }
        public Nullable<int> UnionCouncilId { get; set; }
        public string UnionCouncilCode { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<System.Guid> UpdatedBy { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public Nullable<System.Guid> DeletedBy { get; set; }
        public Nullable<long> UserLogId { get; set; }
        public byte ActionTypeId { get; set; }
        public Nullable<bool> IsRunningHMIS { get; set; }
        public Nullable<bool> IsOffline { get; set; }
    }
}
