//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRReports.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class IcvCertificate
    {
        public System.Guid IcvCertificateId { get; set; }
        public Nullable<System.Guid> PatientId { get; set; }
        public Nullable<System.Guid> PatientVisitId { get; set; }
        public Nullable<System.Guid> PatientDiagnoseId { get; set; }
        public Nullable<int> HealthFacilityId { get; set; }
        public Nullable<System.Guid> DoctorId { get; set; }
        public string OpdNo { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public string Name { get; set; }
        public string RelativeName { get; set; }
        public string CNIC { get; set; }
        public Nullable<System.Guid> NationalityTypeProfileId { get; set; }
        public string PassportNo { get; set; }
        public string Condition { get; set; }
        public string Vaccination { get; set; }
        public string QrCodeImagePath { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string NameOfDisease { get; set; }
        public Nullable<System.DateTime> VaccinationDate { get; set; }
        public Nullable<bool> IsOpdNoGenerated { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<System.Guid> UpdatedBy { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public Nullable<System.Guid> DeletedBy { get; set; }
        public byte ActionTypeId { get; set; }
    }
}
