//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRReports.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LabTest
    {
        public int LabTestId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<System.Guid> DepartmentProfileId { get; set; }
        public Nullable<System.Guid> LabTestCategoryProfileId { get; set; }
        public string SampleType { get; set; }
        public Nullable<decimal> TestPrice { get; set; }
        public Nullable<decimal> DoctorShare { get; set; }
        public Nullable<decimal> StaffShare { get; set; }
        public Nullable<decimal> GovtShare { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<System.Guid> UpdatedBy { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public Nullable<System.Guid> DeletedBy { get; set; }
        public Nullable<long> UserLogId { get; set; }
        public byte ActionTypeId { get; set; }
        public Nullable<System.Guid> LabTestTypeProfileId { get; set; }
        public bool IsSampleRequired { get; set; }
    }
}
