//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRReports.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicineDispatch
    {
        public System.Guid MedicineDispatchId { get; set; }
        public System.Guid PatientId { get; set; }
        public System.Guid PatientVisitId { get; set; }
        public int MedicineId { get; set; }
        public Nullable<int> QuantityPrescribed { get; set; }
        public Nullable<int> QuantityDispatch { get; set; }
        public Nullable<System.Guid> Pharmacist { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<System.Guid> UpdatedBy { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public Nullable<System.Guid> DeletedBy { get; set; }
        public Nullable<long> UserLogId { get; set; }
        public byte ActionTypeId { get; set; }
        public Nullable<int> AvailableQuantity { get; set; }
        public string MedicineName { get; set; }
        public Nullable<bool> MIMSDispatched { get; set; }
        public string BatchNo { get; set; }
        public string Reason { get; set; }
        public Nullable<System.Guid> PatientDiagnoseId { get; set; }
        public Nullable<System.Guid> PatientPrescriptionId { get; set; }
        public Nullable<int> WardId { get; set; }
        public Nullable<System.Guid> MedicineResource { get; set; }
        public Nullable<System.Guid> MedicineResourceProfileId { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<System.Guid> MedicineTypeProfileId { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<int> ExternalQuantity { get; set; }
    }
}
