//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRReports.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MimsGetMedicineResponse
    {
        public System.Guid MimsGetMedicineResponseId { get; set; }
        public Nullable<int> HealthFacilityId { get; set; }
        public string ResponseData { get; set; }
        public Nullable<int> WardId { get; set; }
        public string WardName { get; set; }
        public Nullable<long> MimsIndentId { get; set; }
        public Nullable<bool> SyncStatus { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<byte> ActionTypeId { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public Nullable<System.Guid> DeletedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<System.Guid> UpdatedBy { get; set; }
    }
}
