//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRReports.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MLC
    {
        public System.Guid MLCId { get; set; }
        public Nullable<System.Guid> MLCTypeProfileId { get; set; }
        public System.Guid PatientId { get; set; }
        public System.Guid PatientVisitId { get; set; }
        public Nullable<System.Guid> PatientDiagnoseId { get; set; }
        public Nullable<System.Guid> PatientStatusProfileId { get; set; }
        public Nullable<int> HealthFacilityId { get; set; }
        public Nullable<System.Guid> DoctorId { get; set; }
        public string CaseAgainst { get; set; }
        public Nullable<System.Guid> MCDTypeProfileId { get; set; }
        public Nullable<System.Guid> PCDTypeProfileId { get; set; }
        public string MLCNo { get; set; }
        public string BookNo { get; set; }
        public string PoliceDistrict { get; set; }
        public string ConsentFile { get; set; }
        public string ReasonForChangeDoctor { get; set; }
        public string PoliceDocketOne { get; set; }
        public string PoliceDocketTwo { get; set; }
        public string PoliceDocketThree { get; set; }
        public Nullable<System.Guid> ImageTypeProfileId { get; set; }
        public Nullable<long> ReportCounts { get; set; }
        public string QrCodeImagePath { get; set; }
        public Nullable<bool> IsFinalReport { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<System.Guid> UpdatedBy { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public Nullable<System.Guid> DeletedBy { get; set; }
        public byte ActionTypeId { get; set; }
        public Nullable<bool> IsBookNoGenerated { get; set; }
    }
}
