//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRReports.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MLCPoliceInfo
    {
        public System.Guid MLCPoliceInfoId { get; set; }
        public Nullable<System.Guid> MLCId { get; set; }
        public System.Guid PatientId { get; set; }
        public System.Guid PatientVisitId { get; set; }
        public Nullable<System.Guid> PatientDiagnoseId { get; set; }
        public Nullable<System.Guid> PatientStatusProfileId { get; set; }
        public Nullable<int> HealthFacilityId { get; set; }
        public Nullable<System.Guid> PoliceSignatureTypeProfileId { get; set; }
        public Nullable<System.DateTime> PoliceSignatureDateTime { get; set; }
        public string PolicePersonNameDesignation { get; set; }
        public string PoliceStationName { get; set; }
        public string PolicePeron2NameDesignation { get; set; }
        public string PoliceStationAddress { get; set; }
        public string CommentsByPolice { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<System.Guid> UpdatedBy { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public Nullable<System.Guid> DeletedBy { get; set; }
        public byte ActionTypeId { get; set; }
    }
}
