//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRReports.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MLCSVEvidenceCollected
    {
        public System.Guid MLCSVEvidenceCollectedId { get; set; }
        public Nullable<System.Guid> MLCSVInitialInfoId { get; set; }
        public System.Guid PatientId { get; set; }
        public System.Guid PatientVisitId { get; set; }
        public Nullable<System.Guid> PatientDiagnoseId { get; set; }
        public Nullable<System.Guid> PatientStatusProfileId { get; set; }
        public Nullable<int> HealthFacilityId { get; set; }
        public string ClothsDescription { get; set; }
        public string ClothsHandOverTo { get; set; }
        public string BloodDescription { get; set; }
        public string BloodHandOverTo { get; set; }
        public string VaginalDescription { get; set; }
        public string VaginalHandOverTo { get; set; }
        public string OralDescription { get; set; }
        public string OralHandOverTo { get; set; }
        public string InvestigationAdvice { get; set; }
        public string XRayReason { get; set; }
        public string XRayReport { get; set; }
        public string UltraSoundReason { get; set; }
        public string UltraSoundReport { get; set; }
        public string BloodReason { get; set; }
        public string BloodReport { get; set; }
        public Nullable<System.Guid> CounselingRefferalProfileId { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<System.Guid> UpdatedBy { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public Nullable<System.Guid> DeletedBy { get; set; }
        public byte ActionTypeId { get; set; }
    }
}
