//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRReports.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MLCSVExamination
    {
        public System.Guid MLCSVExaminationId { get; set; }
        public Nullable<System.Guid> MLCSVInitialInfoId { get; set; }
        public System.Guid PatientId { get; set; }
        public System.Guid PatientVisitId { get; set; }
        public Nullable<System.Guid> PatientDiagnoseId { get; set; }
        public Nullable<System.Guid> PatientStatusProfileId { get; set; }
        public Nullable<int> HealthFacilityId { get; set; }
        public string History { get; set; }
        public string VictimDetail { get; set; }
        public Nullable<System.DateTime> IncidenceDateTim { get; set; }
        public string Location { get; set; }
        public string RelationToVictim { get; set; }
        public string AssaultDetail { get; set; }
        public Nullable<bool> PreviousIncidence { get; set; }
        public Nullable<System.DateTime> PreviousIncidenceDateTime { get; set; }
        public string DetailFromOther { get; set; }
        public string RelevantMedicalSurgicalPsychiatricHistory { get; set; }
        public string RelevantGynecologicalHistory { get; set; }
        public string CurrentSymptoms { get; set; }
        public string ClothExamination { get; set; }
        public string TypeOfCloths { get; set; }
        public string CutsTearsHoles { get; set; }
        public string BloodStaining { get; set; }
        public string NonBiologicalMaterialStaining { get; set; }
        public string GeneralPhysicalExamination { get; set; }
        public string Physique { get; set; }
        public string Confident { get; set; }
        public string Confused { get; set; }
        public string HeightWeight1 { get; set; }
        public string CharacteristicsOfInjuries { get; set; }
        public string Tears { get; set; }
        public string Rupture { get; set; }
        public string EvidenceBleed { get; set; }
        public string EvidenceSeminal { get; set; }
        public string Reference { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<System.Guid> UpdatedBy { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public Nullable<System.Guid> DeletedBy { get; set; }
        public byte ActionTypeId { get; set; }
    }
}
