//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRReports.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MLCSVReport
    {
        public System.Guid MLCSVReportId { get; set; }
        public Nullable<System.Guid> MLCSVInitialInfoId { get; set; }
        public System.Guid PatientId { get; set; }
        public System.Guid PatientVisitId { get; set; }
        public Nullable<System.Guid> PatientDiagnoseId { get; set; }
        public Nullable<System.Guid> PatientStatusProfileId { get; set; }
        public Nullable<int> HealthFacilityId { get; set; }
        public string NatureOfInjuries { get; set; }
        public string DurationOfInjuries { get; set; }
        public string KindOfWeaponUse { get; set; }
        public string Treatment { get; set; }
        public string Notes { get; set; }
        public string KUOInjuryNote { get; set; }
        public string FinalOpinion { get; set; }
        public Nullable<System.Guid> ManualReportImageId { get; set; }
        public Nullable<System.Guid> FinalReportImageId { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<System.Guid> UpdatedBy { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public Nullable<System.Guid> DeletedBy { get; set; }
        public byte ActionTypeId { get; set; }
    }
}
