//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRReports.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MLEBasicInfo
    {
        public System.Guid MLEBasicInfoId { get; set; }
        public System.Guid MLCId { get; set; }
        public System.Guid PatientId { get; set; }
        public System.Guid PatientVisitId { get; set; }
        public Nullable<System.Guid> PatientDiagnoseId { get; set; }
        public Nullable<System.Guid> PatientStatusProfileId { get; set; }
        public Nullable<int> HealthFacilityId { get; set; }
        public Nullable<System.Guid> PatientImageProfileId { get; set; }
        public Nullable<System.Guid> PoliceSignatureProfileId { get; set; }
        public Nullable<System.Guid> PatientSignatureProfileId { get; set; }
        public Nullable<System.Guid> AdultOrUnderAgeFingerPrintProfileId { get; set; }
        public Nullable<System.Guid> PoliceFingerPrintProfileId { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Relation { get; set; }
        public Nullable<System.DateTime> MlcDate { get; set; }
        public Nullable<int> RefferToHealthFacilityId { get; set; }
        public Nullable<System.Guid> CaseTypeProfileId { get; set; }
        public string IncidentPlace { get; set; }
        public string MlcRemark1 { get; set; }
        public string MlcRemark2 { get; set; }
        public string AccompaniesBy { get; set; }
        public Nullable<System.DateTime> ArrivalDateTime { get; set; }
        public Nullable<System.DateTime> ExaminationDateTime { get; set; }
        public string CourtOrder { get; set; }
        public string PoliceConstableName { get; set; }
        public string PoliceConstablePhoneNumber { get; set; }
        public Nullable<System.DateTime> AdmitDateTime { get; set; }
        public Nullable<System.DateTime> DischargeDateTime { get; set; }
        public string Comments { get; set; }
        public Nullable<System.DateTime> SentDateTime { get; set; }
        public Nullable<long> ReportCounts { get; set; }
        public Nullable<bool> IsFinalReport { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<System.Guid> UpdatedBy { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public Nullable<System.Guid> DeletedBy { get; set; }
        public Nullable<byte> ActionTypeId { get; set; }
    }
}
