//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRReports.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MLEExamination
    {
        public System.Guid MLEExaminationId { get; set; }
        public System.Guid MLEBasicInfoId { get; set; }
        public System.Guid PatientId { get; set; }
        public System.Guid PatientVisitId { get; set; }
        public Nullable<System.Guid> PatientDiagnoseId { get; set; }
        public Nullable<System.Guid> PatientStatusProfileId { get; set; }
        public Nullable<int> HealthFacilityId { get; set; }
        public string History { get; set; }
        public string ClothExamination { get; set; }
        public string GeneralPhysicalExamination { get; set; }
        public string InjuriesDescription { get; set; }
        public string AdvisedInvestigate { get; set; }
        public string LaboratoryInvestigation { get; set; }
        public string OpinionSpecialistOrXRayReport { get; set; }
        public string NatureOfInjuries { get; set; }
        public string Fabrication { get; set; }
        public string DurationOfInjuries { get; set; }
        public string WeaponPoison { get; set; }
        public string KuoInjuries { get; set; }
        public Nullable<long> ReportCounts { get; set; }
        public Nullable<bool> IsFinalReport { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<System.Guid> UpdatedBy { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public Nullable<System.Guid> DeletedBy { get; set; }
        public Nullable<byte> ActionTypeId { get; set; }
    }
}
