//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRReports.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MSsavedforeignkeycolumns
    {
        public string program_name { get; set; }
        public string constraint_name { get; set; }
        public string parent_schema { get; set; }
        public int constraint_column_id { get; set; }
        public string referencing_column_name { get; set; }
        public string referenced_column_name { get; set; }
        public System.DateTime timestamp { get; set; }
    }
}
