//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRReports.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OfflineVersionLog
    {
        public System.Guid OfflineVersionLogId { get; set; }
        public int HealthFacilityId { get; set; }
        public System.Guid ProjectProfileId { get; set; }
        public string VersionNumber { get; set; }
        public System.DateTime ReleaseDate { get; set; }
        public string IP_Address { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.Guid CreatedBy { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public Nullable<System.Guid> DeletedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<System.Guid> UpdatedBy { get; set; }
        public bool IsActive { get; set; }
        public byte ActionTypeId { get; set; }
    }
}
