//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRReports.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OfflineServerDataSyncLog
    {
        public System.Guid OfflineServerDataSyncLogId { get; set; }
        public Nullable<System.DateTime> LastSync { get; set; }
        public Nullable<int> HealthFacilityId { get; set; }
    }
}
