//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRReports.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OutSourceSystemLog
    {
        public System.Guid OutSourceSystemLogId { get; set; }
        public Nullable<System.Guid> SourceSystemId { get; set; }
        public string UserSystemIp { get; set; }
        public string TargetedApiUrl { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public string InputParameters { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    }
}
