//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRReports.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientPrescription
    {
        public System.Guid PatientPrescriptionId { get; set; }
        public Nullable<System.Guid> PatientId { get; set; }
        public Nullable<System.Guid> PatientVisitId { get; set; }
        public Nullable<System.Guid> PatientDiagnoseId { get; set; }
        public Nullable<int> MedicineId { get; set; }
        public Nullable<System.Guid> MedicineTypeId { get; set; }
        public Nullable<int> Days { get; set; }
        public Nullable<System.Guid> DoseProfileId { get; set; }
        public Nullable<System.Guid> DoseTimeProfileId { get; set; }
        public Nullable<System.Guid> PrescribedBy { get; set; }
        public Nullable<int> Quantity { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<System.Guid> UpdatedBy { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public Nullable<System.Guid> DeletedBy { get; set; }
        public Nullable<long> UserLogId { get; set; }
        public byte ActionTypeId { get; set; }
        public string MedicineName { get; set; }
        public Nullable<int> AvailableQuantity { get; set; }
        public Nullable<decimal> MorningDose { get; set; }
        public Nullable<decimal> AfterNoonDose { get; set; }
        public Nullable<decimal> EveningDose { get; set; }
        public Nullable<decimal> NightDose { get; set; }
        public Nullable<bool> BeforeFood { get; set; }
        public Nullable<bool> AfterFood { get; set; }
        public Nullable<bool> BeforeBreakFast { get; set; }
        public string MedicineDose { get; set; }
        public string MedicineRoute { get; set; }
        public string MedicineFrequency { get; set; }
        public string MedicineInstruction { get; set; }
        public string MedicineDuration { get; set; }
        public string BatchNo { get; set; }
        public Nullable<System.Guid> MedicineResource { get; set; }
        public Nullable<System.Guid> MedicineResourceProfileId { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<System.Guid> MedicineTypeProfileId { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<byte> Status { get; set; }
        public Nullable<System.Guid> MedicineAdvisedRequisitionId { get; set; }
        public Nullable<System.Guid> MedicineAdvisedId { get; set; }
        public Nullable<bool> IsSMLMedicine { get; set; }
    }
}
