//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRReports.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientSourceInfo
    {
        public System.Guid PatientSourceInfoId { get; set; }
        public Nullable<System.Guid> PatientId { get; set; }
        public Nullable<System.Guid> UnknownPatientId { get; set; }
        public Nullable<System.Guid> PatientSourceProfileId { get; set; }
        public string VehicleNo { get; set; }
        public string Designation { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.Guid> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<System.Guid> DeleteBy { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public Nullable<byte> ActionTypeId { get; set; }
        public string Name { get; set; }
        public string ContactNo { get; set; }
    }
}
