//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRReports.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientOpenVisitLog
    {
        public System.Guid PatientOpenVisitId { get; set; }
        public string SlipNo { get; set; }
        public string TokenNo { get; set; }
        public Nullable<int> VisitNo { get; set; }
        public Nullable<System.Guid> VisitTypeProfileId { get; set; }
        public Nullable<bool> IsReferred { get; set; }
        public Nullable<int> ReferredHealthFacilityId { get; set; }
        public Nullable<int> ReferredDepartmentLookupId { get; set; }
        public Nullable<int> ReferredSectionLookupId { get; set; }
        public Nullable<System.Guid> ReferredBy { get; set; }
        public Nullable<System.Guid> PatientId { get; set; }
        public Nullable<int> HealthFacilityId { get; set; }
        public Nullable<int> DepartementLookupId { get; set; }
        public Nullable<int> SectionLookupId { get; set; }
        public Nullable<System.Guid> CurrentStationProfileId { get; set; }
        public Nullable<System.Guid> CurrentStationUserId { get; set; }
        public Nullable<System.DateTime> VisitDate { get; set; }
        public Nullable<System.Guid> VitalCollectedBy { get; set; }
        public bool IsFromPMIS { get; set; }
        public Nullable<System.Guid> AttendedBy { get; set; }
        public Nullable<System.Guid> PharmacyAttendedBy { get; set; }
        public bool IsWillingToBuyMedPrivately { get; set; }
        public Nullable<bool> IsDischarge { get; set; }
        public Nullable<bool> IsVisitExternally { get; set; }
        public string SourceVisitId { get; set; }
        public Nullable<int> SourceSystemIdd { get; set; }
        public string SourceHealthFacilityId { get; set; }
        public string SourceReferredHealthFacilityId { get; set; }
        public Nullable<bool> IsVitalSkip { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<System.Guid> UpdatedBy { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public Nullable<System.Guid> DeletedBy { get; set; }
        public Nullable<long> UserLogId { get; set; }
        public byte ActionTypeId { get; set; }
        public System.DateTime ActionDate { get; set; }
        public Nullable<System.Guid> SourceSystemId { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<System.Guid> AgeTypeProfileId { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> IsAdmittedInIPD { get; set; }
        public Nullable<bool> IsOccupied { get; set; }
        public Nullable<System.Guid> OccupiedBy { get; set; }
        public Nullable<bool> IsEligibleForSsc { get; set; }
        public string SscNumber { get; set; }
        public Nullable<bool> IsSscClaimed { get; set; }
        public Nullable<System.Guid> ReasonIfSscNotClaimed { get; set; }
        public Nullable<System.DateTime> SscClaimedDate { get; set; }
        public Nullable<System.Guid> ReasonIfNotEligibleForSsc { get; set; }
        public Nullable<bool> IsReferredIpd { get; set; }
        public Nullable<int> IpdDepartmentLookupId { get; set; }
        public Nullable<int> IpdSectionLookupId { get; set; }
        public Nullable<System.Guid> IpdReferredBy { get; set; }
        public Nullable<int> IpdReferredByDepartmentLookupId { get; set; }
        public Nullable<System.Guid> ParentPatientOpenVisitId { get; set; }
        public Nullable<int> IpdReferredBySectionLookupId { get; set; }
        public Nullable<bool> IsAutoGenerated { get; set; }
        public Nullable<bool> IsFromCallCenter { get; set; }
        public Nullable<bool> IsDrugAddict { get; set; }
        public Nullable<int> SscStatus { get; set; }
        public Nullable<System.Guid> SscStatusUpdatedBy { get; set; }
        public Nullable<System.DateTime> SscStatusUpdatedOn { get; set; }
        public string SscStatusReason { get; set; }
        public Nullable<int> BedNo { get; set; }
        public Nullable<int> PatinetPrivateHeathFacilityId { get; set; }
        public Nullable<System.Guid> PatientConditionProfileId { get; set; }
        public string VisitFor { get; set; }
        public Nullable<byte> VisitSource { get; set; }
        public Nullable<bool> IsAdmitted { get; set; }
    }
}
