//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRReports.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientAssessment
    {
        public System.Guid PatientAssessmentId { get; set; }
        public Nullable<System.Guid> PatientId { get; set; }
        public Nullable<System.Guid> PatientDiagnoseId { get; set; }
        public Nullable<System.Guid> PatientVisitId { get; set; }
        public Nullable<bool> IsFrequentTherapeuticInjections { get; set; }
        public Nullable<bool> IsConfirmedCaseOfSTDs { get; set; }
        public Nullable<bool> IsInvasiveMedAndSurgIntervention { get; set; }
        public string SurgeryType { get; set; }
        public Nullable<System.DateTime> SurgeryDate { get; set; }
        public Nullable<bool> IsCloseContactKnownCaseOfHcvOrHbv { get; set; }
        public Nullable<bool> IsCloseContactUnderTreatment { get; set; }
        public Nullable<bool> IsBloodTransfusion { get; set; }
        public Nullable<System.DateTime> BloodTransfusionYear { get; set; }
        public string BloodTransfusionBloodBank { get; set; }
        public Nullable<bool> IsConfirmedHIVPositivePersons { get; set; }
        public Nullable<bool> IsEverBeenHospitalized { get; set; }
        public Nullable<bool> IsHospitalizedBeenLastTwoYear { get; set; }
        public Nullable<bool> IsIndividualsWithTattooing { get; set; }
        public Nullable<bool> IsInjectableDrugUser { get; set; }
        public Nullable<bool> IsDentalIntervention { get; set; }
        public string DentalClinic { get; set; }
        public Nullable<bool> IsHistoryofMultipleSexPartners { get; set; }
        public Nullable<bool> IsTruckDriver { get; set; }
        public Nullable<bool> IsEarNosePiercing { get; set; }
        public Nullable<bool> IsTransgender { get; set; }
        public Nullable<bool> IsSharingOfToothBrush { get; set; }
        public Nullable<bool> IsSharingOfHairComb { get; set; }
        public Nullable<bool> IsDarkColoredUrine { get; set; }
        public Nullable<bool> IsLossOfAppetite { get; set; }
        public Nullable<bool> IsLightColoredFaeces { get; set; }
        public Nullable<bool> IsFatigue { get; set; }
        public Nullable<bool> IsMusclePain { get; set; }
        public Nullable<bool> IsNausea { get; set; }
        public Nullable<bool> IsStomachAche { get; set; }
        public Nullable<bool> IsRightUpperQuadrantTenderness { get; set; }
        public Nullable<bool> IsGastricIrritationBurning { get; set; }
        public Nullable<bool> IsUnusualUrethralDischarge { get; set; }
        public string AdvisedSampleCollection { get; set; }
        public string MONotes { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<System.Guid> UpdatedBy { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public Nullable<System.Guid> DeletedBy { get; set; }
        public Nullable<long> UserLogId { get; set; }
        public byte ActionTypeId { get; set; }
    }
}
