//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRReports.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientVisitToken
    {
        public System.Guid PatientVisitTokenId { get; set; }
        public int HealthFacilityId { get; set; }
        public Nullable<int> DepartmentLookupId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> TokenNo { get; set; }
    }
}
