//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRReports.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientNadraRequest
    {
        public System.Guid PatientNadraRequestId { get; set; }
        public Nullable<System.Guid> PatientId { get; set; }
        public string LocationId { get; set; }
        public Nullable<int> RequestId { get; set; }
        public Nullable<int> RequestCode { get; set; }
        public string FingerPrintFormate { get; set; }
        public Nullable<System.Guid> StatusProfileId { get; set; }
        public Nullable<bool> IsTransactionSaveSuccessfully { get; set; }
        public Nullable<bool> IsPendingVerification { get; set; }
        public int RequestCount { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<System.Guid> UpdatedBy { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public Nullable<System.Guid> DeletedBy { get; set; }
        public Nullable<byte> ActionTypeId { get; set; }
    }
}
