//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRReports.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientEyeBlindness
    {
        public System.Guid PatientEyeBlindnessId { get; set; }
        public Nullable<System.Guid> PatientId { get; set; }
        public Nullable<System.Guid> PatientVisitId { get; set; }
        public string ComorbidityBy { get; set; }
        public Nullable<System.DateTime> DateOfInocvlation { get; set; }
        public string ConsultantName { get; set; }
        public string StatusOfVision { get; set; }
        public string Recovery { get; set; }
        public Nullable<int> HospitalInjectedId { get; set; }
        public Nullable<int> HealthfacilityId { get; set; }
        public string OtherHealthFacility { get; set; }
        public string EyeInvolved { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.Guid> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public Nullable<System.Guid> DeletedBy { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<byte> ActionTypeId { get; set; }
    }
}
