//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRReports.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientDiagnose
    {
        public System.Guid PatientDiagnoseId { get; set; }
        public Nullable<System.Guid> PatientId { get; set; }
        public Nullable<System.Guid> PatientVisitId { get; set; }
        public Nullable<System.Guid> OutcomeStatusProfileId { get; set; }
        public string FormType { get; set; }
        public string PresentComplaints { get; set; }
        public string Examination { get; set; }
        public string PatientMedicalHistory { get; set; }
        public string AdviseGiven { get; set; }
        public Nullable<System.DateTime> FollowupDate { get; set; }
        public int DoctorVisitNo { get; set; }
        public Nullable<int> DocDepartmentLookupId { get; set; }
        public Nullable<int> DocSectionLookupId { get; set; }
        public Nullable<System.Guid> DiagnosedBy { get; set; }
        public Nullable<bool> IsDiagnoseExternally { get; set; }
        public string SourceDoctorName { get; set; }
        public bool IsActive { get; set; }
        public Nullable<bool> IsConfirmed { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<System.Guid> UpdatedBy { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public Nullable<System.Guid> DeletedBy { get; set; }
        public Nullable<long> UserLogId { get; set; }
        public byte ActionTypeId { get; set; }
        public Nullable<bool> IsVerifiedByConsultant { get; set; }
        public Nullable<System.Guid> MedicineResourceProfileId { get; set; }
        public Nullable<bool> IsAutoGenerated { get; set; }
        public Nullable<bool> IsMlc { get; set; }
        public Nullable<bool> IsFromCallCenter { get; set; }
        public Nullable<System.Guid> SourceSystemId { get; set; }
        public Nullable<bool> IsSendToCdc { get; set; }
        public Nullable<System.Guid> MedicineRegimeProfileId { get; set; }
        public Nullable<bool> AnyMedicineReaction { get; set; }
        public string ReactionNote { get; set; }
        public Nullable<bool> IsDischargeDiagnose { get; set; }
        public Nullable<int> PatientVisitCount { get; set; }
        public Nullable<System.Guid> PatientVisitTypeProfileId { get; set; }
        public Nullable<System.Guid> SvrStatusProfileId { get; set; }
        public Nullable<System.Guid> PcrStatusProfileId { get; set; }
        public Nullable<System.Guid> FollowupDateTypeProfileId { get; set; }
        public Nullable<int> ReferToDepartmentLookupId { get; set; }
        public Nullable<int> ReferToSectionLookupId { get; set; }
        public Nullable<bool> IsRefer { get; set; }
        public Nullable<bool> IsGynaePatient { get; set; }
    }
}
