//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRReports.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientDiagnosisRecord
    {
        public System.Guid PatientDiagnosisRecordId { get; set; }
        public System.Guid PatientVisitId { get; set; }
        public System.Guid PatientId { get; set; }
        public System.Guid PatientDiagnoseId { get; set; }
        public string FormType { get; set; }
        public string Json { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.Guid> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<System.Guid> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public byte ActionTypeId { get; set; }
        public Nullable<bool> IsPrinted { get; set; }
    }
}
