//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRReports.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientAdmissionDetailLog
    {
        public System.Guid PatientAdmissionDetailId { get; set; }
        public System.Guid PatientId { get; set; }
        public System.Guid PatientVisitId { get; set; }
        public Nullable<System.Guid> PatientDiagnoseId { get; set; }
        public Nullable<int> ShiftedFromDepartmentLookupId { get; set; }
        public Nullable<int> ShiftedFromSectionLookupId { get; set; }
        public Nullable<int> DepartmentLookupId { get; set; }
        public Nullable<int> SectionLookupId { get; set; }
        public Nullable<System.Guid> PatientStatusProfileId { get; set; }
        public string ReasonOfShifting { get; set; }
        public string ShiftedBy { get; set; }
        public Nullable<System.DateTime> ShiftedOn { get; set; }
        public string AdmittedBy { get; set; }
        public Nullable<System.DateTime> AdmittedInSpeciality { get; set; }
        public Nullable<System.Guid> PatientLevelProfileId { get; set; }
        public Nullable<bool> IsVantilated { get; set; }
        public Nullable<System.DateTime> PatientAdmittedOn { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<System.Guid> UpdatedBy { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public Nullable<System.Guid> DeletedBy { get; set; }
        public byte ActionTypeId { get; set; }
        public System.DateTime ActionDate { get; set; }
        public Nullable<int> IpdVisitNo { get; set; }
        public Nullable<int> IpdSource { get; set; }
        public Nullable<int> ShiftedFromHealthFacilityId { get; set; }
        public Nullable<int> HealthFacilityId { get; set; }
        public Nullable<bool> IsDischarge { get; set; }
    }
}
