//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRReports.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientLabTestDetail
    {
        public System.Guid PatientLabTestDetailId { get; set; }
        public System.Guid PatientLabTestId { get; set; }
        public Nullable<int> LabTestId { get; set; }
        public string TestName { get; set; }
        public string TestNormalValue { get; set; }
        public string MinValue { get; set; }
        public string MaxValue { get; set; }
        public string TestUnit { get; set; }
        public Nullable<int> SequenceNo { get; set; }
        public string Result { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.Guid> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public Nullable<System.Guid> DeletedBy { get; set; }
        public Nullable<long> UserLogId { get; set; }
        public byte ActionTypeId { get; set; }
        public Nullable<System.Guid> TestResultDropDownTypeProfileId { get; set; }
        public string TestResultInputType { get; set; }
        public string TestResultInputValue { get; set; }
    }
}
