//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRReports.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientVitals
    {
        public System.Guid PatientVitalId { get; set; }
        public Nullable<System.Guid> PatientId { get; set; }
        public Nullable<System.Guid> PatientVisitId { get; set; }
        public string BPSystolic { get; set; }
        public string BPDiaSystolic { get; set; }
        public string Pulse { get; set; }
        public string Temprature { get; set; }
        public string Weight { get; set; }
        public string Height { get; set; }
        public string ResperatoryRate { get; set; }
        public Nullable<System.Guid> VitalsCollectedBy { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<System.Guid> UpdatedBy { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public Nullable<System.Guid> DeletedBy { get; set; }
        public Nullable<long> UserLogId { get; set; }
        public byte ActionTypeId { get; set; }
        public string BMI { get; set; }
        public string JsonRecord { get; set; }
        public Nullable<bool> IsChangeBPSystolic { get; set; }
        public Nullable<bool> IsChangeBPDiaSystolic { get; set; }
        public Nullable<bool> IsChangePulse { get; set; }
        public Nullable<bool> IsChangeTemprature { get; set; }
        public Nullable<bool> IsChangeWeight { get; set; }
        public Nullable<bool> IsChangeHeight { get; set; }
        public Nullable<bool> IsChangeResperatoryRate { get; set; }
        public Nullable<bool> IsChangeBMI { get; set; }
    }
}
