//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRReports.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientDocument
    {
        public System.Guid PatientDocumentId { get; set; }
        public System.Guid PatientId { get; set; }
        public Nullable<System.Guid> PatientVisitId { get; set; }
        public Nullable<System.Guid> PatientDocumentTypeProfileId { get; set; }
        public Nullable<System.Guid> DocumentProfileId { get; set; }
        public string DocumentName { get; set; }
        public string Url { get; set; }
        public string Base64 { get; set; }
        public Nullable<byte> Status { get; set; }
        public string StatusReason { get; set; }
        public Nullable<System.DateTime> StatusUpdatedOn { get; set; }
        public Nullable<System.Guid> StatusUpdatedBy { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.Guid> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<System.Guid> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public byte ActionTypeId { get; set; }
    }
}
