//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRReports.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientStatusBySpeciality
    {
        public System.Guid PatientStatusBySpecialityId { get; set; }
        public Nullable<System.Guid> PatientId { get; set; }
        public Nullable<System.Guid> PatientVisitId { get; set; }
        public Nullable<System.Guid> PatientDiagnoseId { get; set; }
        public Nullable<int> HealthFacilityId { get; set; }
        public Nullable<int> DepartmentLookupId { get; set; }
        public Nullable<int> SectionLookupId { get; set; }
        public Nullable<System.Guid> PatientStatusProfileId { get; set; }
        public string DeseaseSubType { get; set; }
        public string TbPatientConfirmationType { get; set; }
        public string FormType { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<System.Guid> UpdatedBy { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public Nullable<System.Guid> DeletedBy { get; set; }
        public Nullable<byte> ActionTypeId { get; set; }
    }
}
