//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRReports.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientDiagnoseProcedure
    {
        public System.Guid PatientDiagnoseProcedureId { get; set; }
        public Nullable<System.Guid> PatientDiagnoseId { get; set; }
        public Nullable<int> SectionProcedureId { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<System.Guid> UpdatedBy { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public Nullable<System.Guid> DeletedBy { get; set; }
        public byte ActionTypeId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.Guid> RecommendBy { get; set; }
        public Nullable<System.Guid> PerformedBy { get; set; }
        public string Feedback { get; set; }
        public Nullable<bool> IsPerformed { get; set; }
        public Nullable<System.Guid> DentalDiseaseProfileId { get; set; }
        public Nullable<System.Guid> ToothPositionProfileId { get; set; }
        public Nullable<System.Guid> ToothNumberProfileId { get; set; }
        public string ToothNumber { get; set; }
        public string ToothPosition { get; set; }
        public Nullable<System.Guid> AssistedBy { get; set; }
        public Nullable<System.Guid> PatientVisitId { get; set; }
    }
}
