//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRReports.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public int Id { get; set; }
        public Nullable<long> Entity_Id { get; set; }
        public Nullable<int> PersonType_Id { get; set; }
        public string NameTitle { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string CNIC { get; set; }
        public Nullable<int> CNICRelation_Id { get; set; }
        public string CNICRelationName { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Gender { get; set; }
        public string BloodGroup { get; set; }
        public string MobileNumber { get; set; }
        public string MobileNumberSecondary { get; set; }
        public string Email { get; set; }
        public string EmailSecondary { get; set; }
        public string LandlineNumber { get; set; }
        public Nullable<int> NationalTaxNumber { get; set; }
        public string PermanentAddress { get; set; }
        public string CorrespondenceAddress { get; set; }
        public Nullable<int> Religion_Id { get; set; }
        public Nullable<int> MaritalStatus_Id { get; set; }
        public Nullable<int> Domicile_Id { get; set; }
        public string Source { get; set; }
        public string HFMISCode { get; set; }
        public string FatherName { get; set; }
        public string Nationality { get; set; }
        public string PassportNo { get; set; }
        public string PlaceOfBirth { get; set; }
        public string Caste { get; set; }
        public string PostalCode { get; set; }
        public Nullable<int> Age { get; set; }
        public string HealthFacilityName { get; set; }
        public bool IsRegisteredHMIS { get; set; }
    }
}
