//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRReports.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhysiotherapyForm
    {
        public System.Guid PhysiotherapyFormId { get; set; }
        public System.Guid PatientDiagnoseId { get; set; }
        public string PresentingComplaint { get; set; }
        public Nullable<System.DateTime> ProblemSince { get; set; }
        public string AnyComorbidity { get; set; }
        public string DrugHistory { get; set; }
        public string SignificantExaminationFindings { get; set; }
        public string TotalDurationOfTreatmentSession { get; set; }
        public Nullable<bool> DischargeFromPhysicalTherapyTreatment { get; set; }
        public Nullable<bool> HomeExercisePlan { get; set; }
        public Nullable<bool> TreatmentAtDepartment { get; set; }
        public string Prognosis { get; set; }
        public string ClinicalDiagnosis { get; set; }
        public string PhysiotherapyDiagnosis { get; set; }
        public string KeyTreatment { get; set; }
        public string PlanOfCare { get; set; }
        public string FrequencyOfExercise { get; set; }
        public string IntensityOfExercise { get; set; }
        public string TypeOfExercise { get; set; }
        public Nullable<System.Guid> DischargePlanOfCareProfileId { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.Guid> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<System.Guid> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public byte ActionTypeId { get; set; }
    }
}
