//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRReports.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PostmortemReport
    {
        public System.Guid PostmortemReportId { get; set; }
        public Nullable<System.Guid> MLCPostmortemId { get; set; }
        public System.Guid PatientId { get; set; }
        public System.Guid PatientVisitId { get; set; }
        public Nullable<System.Guid> PatientDiagnoseId { get; set; }
        public Nullable<System.Guid> PatientStatusProfileId { get; set; }
        public Nullable<int> HealthFacilityId { get; set; }
        public string ArticalToPolice { get; set; }
        public string DoctorOpinion { get; set; }
        public string ElapsedPortableTime { get; set; }
        public string TimeBetweenInjuryAndDeath { get; set; }
        public string TimeBetweenDeathAndPostmortem { get; set; }
        public string LabExpertReport { get; set; }
        public string FinalOpinion { get; set; }
        public string PoliceOfficerName { get; set; }
        public string PoliceOfficerMobileNo { get; set; }
        public Nullable<System.DateTime> ReportHandoverDatetime { get; set; }
        public Nullable<System.Guid> PoliceSignatureImageId { get; set; }
        public Nullable<System.Guid> PoliceFingerPrintId { get; set; }
        public Nullable<System.Guid> PatientManualReportId { get; set; }
        public Nullable<System.Guid> PatientDrawImgId { get; set; }
        public Nullable<bool> ChemicalExam { get; set; }
        public Nullable<bool> DNALab { get; set; }
        public Nullable<bool> Histopathologist { get; set; }
        public Nullable<bool> BallisticExpert { get; set; }
        public Nullable<bool> IsFinalReport { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<System.Guid> UpdatedBy { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public Nullable<System.Guid> DeletedBy { get; set; }
        public byte ActionTypeId { get; set; }
    }
}
