//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRReports.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PostMortemInternalExamination
    {
        public System.Guid PostMortemInternalExaminationId { get; set; }
        public Nullable<System.Guid> MLCPostmortemId { get; set; }
        public System.Guid PatientId { get; set; }
        public System.Guid PatientVisitId { get; set; }
        public Nullable<System.Guid> PatientDiagnoseId { get; set; }
        public Nullable<System.Guid> PatientStatusProfileId { get; set; }
        public Nullable<int> HealthFacilityId { get; set; }
        public string Scalp { get; set; }
        public string Skull { get; set; }
        public string Membranes { get; set; }
        public string Brain { get; set; }
        public string Vertebrae { get; set; }
        public string SpinalCord { get; set; }
        public string WallsStemum { get; set; }
        public string Pleurae { get; set; }
        public string LaryNx { get; set; }
        public string RightLung { get; set; }
        public string LeftLung { get; set; }
        public string Pencardium { get; set; }
        public string BloodVes { get; set; }
        public string Walls { get; set; }
        public string Peritoneum { get; set; }
        public string Mouth { get; set; }
        public string Diaphragm { get; set; }
        public string StomachContents { get; set; }
        public string Pancrease { get; set; }
        public string SIntestineContents { get; set; }
        public string LIntestineContents { get; set; }
        public string Liver { get; set; }
        public string Spleen { get; set; }
        public string RKidneys { get; set; }
        public string LKidneys { get; set; }
        public string Unnary { get; set; }
        public string Organs { get; set; }
        public string ULInjuries { get; set; }
        public string ULDisease { get; set; }
        public string ULFracutre { get; set; }
        public string ULDislocation { get; set; }
        public string LLInjuries { get; set; }
        public string LLDisease { get; set; }
        public string LLFracutre { get; set; }
        public string LLDislocation { get; set; }
        public Nullable<bool> ChemicalExam { get; set; }
        public Nullable<bool> DNALab { get; set; }
        public Nullable<bool> Histopathologist { get; set; }
        public Nullable<bool> BallisticExpert { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<System.Guid> UpdatedBy { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public Nullable<System.Guid> DeletedBy { get; set; }
        public byte ActionTypeId { get; set; }
    }
}
