//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRReports.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PostmortemExternalExamination
    {
        public System.Guid PostmortemExternalExaminationId { get; set; }
        public Nullable<System.Guid> MLCPostmortemId { get; set; }
        public System.Guid PatientId { get; set; }
        public System.Guid PatientVisitId { get; set; }
        public Nullable<System.Guid> PatientDiagnoseId { get; set; }
        public Nullable<System.Guid> PatientStatusProfileId { get; set; }
        public Nullable<int> HealthFacilityId { get; set; }
        public string PhysicalRemarks { get; set; }
        public string ClothRemarks { get; set; }
        public string NeckRemarks { get; set; }
        public string InjuriesRemarks { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<System.Guid> UpdatedBy { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public Nullable<System.Guid> DeletedBy { get; set; }
        public byte ActionTypeId { get; set; }
    }
}
