//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRReports.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profile
    {
        public System.Guid ProfileId { get; set; }
        public Nullable<int> ProfileAutoId { get; set; }
        public string Name { get; set; }
        public string ShortName { get; set; }
        public Nullable<int> SequenceNo { get; set; }
        public string Description { get; set; }
        public System.Guid ProfileTypeId { get; set; }
        public Nullable<bool> IsDssDisease { get; set; }
        public Nullable<System.Guid> ParentProfileId { get; set; }
        public Nullable<int> ChartPieSequenceNo { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<System.Guid> UpdatedBy { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public Nullable<System.Guid> DeletedBy { get; set; }
        public Nullable<long> UserLogId { get; set; }
        public byte ActionTypeId { get; set; }
        public Nullable<int> SectionId { get; set; }
    }
}
