//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRReports.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PsychologicalAssessment
    {
        public System.Guid PsychologicalAssessmentId { get; set; }
        public Nullable<System.Guid> PatientId { get; set; }
        public Nullable<System.Guid> PatientVisitId { get; set; }
        public Nullable<System.Guid> PatientDiagnoseId { get; set; }
        public string MentalStatusExamination { get; set; }
        public string Appearance { get; set; }
        public string Orientation { get; set; }
        public string Speech { get; set; }
        public string ThroughProcess { get; set; }
        public string ThroughContent { get; set; }
        public string PerceptualProcess { get; set; }
        public string Insight { get; set; }
        public string Judgment { get; set; }
        public string Mood { get; set; }
        public string Affect { get; set; }
        public string Memory { get; set; }
        public string EstimatedIntellectualFunctioning { get; set; }
        public string CognitiveDeficits { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<System.Guid> UpdatedBy { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public Nullable<System.Guid> DeletedBy { get; set; }
        public Nullable<byte> ActionTypeId { get; set; }
    }
}
