//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRReports.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RiderStatusLog
    {
        public System.Guid PatientLabTestId { get; set; }
        public Nullable<System.Guid> PatientId { get; set; }
        public Nullable<System.Guid> PatientVisitId { get; set; }
        public Nullable<System.Guid> PatientDiagnoseId { get; set; }
        public byte Status { get; set; }
        public Nullable<System.Guid> StatusUpdatedBy { get; set; }
        public Nullable<System.DateTime> StatusUpdatedOn { get; set; }
        public Nullable<System.Guid> RiderUserId { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<System.Guid> UpdatedBy { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public Nullable<System.Guid> DeletedBy { get; set; }
        public Nullable<long> UserLogId { get; set; }
        public byte ActionTypeId { get; set; }
        public System.DateTime ActionDate { get; set; }
    }
}
