//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRReports.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SocialWelfareAssignDoctor
    {
        public System.Guid SwDoctorAssignId { get; set; }
        public System.Guid DoctorId { get; set; }
        public System.Guid PatientId { get; set; }
        public System.Guid VisitId { get; set; }
        public System.Guid SocialWellfareFormId { get; set; }
        public int ProvinceId { get; set; }
        public int DivisionId { get; set; }
        public int DistrictId { get; set; }
        public Nullable<bool> isAssignDoctor { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedBy { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public Nullable<System.Guid> DeletedBy { get; set; }
        public Nullable<long> UserLogId { get; set; }
        public Nullable<int> ActionTypeId { get; set; }
    }
}
