//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRReports.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SocialWelfareForms
    {
        public System.Guid Id { get; set; }
        public System.Guid FormTypeProfileId { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<System.Guid> UpdatedBy { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public Nullable<System.Guid> DeletedBy { get; set; }
        public long UserLogId { get; set; }
        public byte ActionTypeId { get; set; }
        public Nullable<int> ReferDistrictId { get; set; }
        public Nullable<System.Guid> PatientVistId { get; set; }
        public Nullable<System.Guid> PatientId { get; set; }
        public string MDRCProfession { get; set; }
        public string MDRCMonthlyIncome { get; set; }
        public string MDRCFHRDrugAddiction { get; set; }
        public string MDRCIfYesRelation { get; set; }
        public string MDRCFamilyAttitude { get; set; }
        public string MDRCPatientAttitude { get; set; }
        public string MDRCCFODAbuse { get; set; }
        public string MDRCDetailOfCounsellingSessionsSesssionI { get; set; }
        public string MDRCDetailOfCounsellingSessionsSesssionII { get; set; }
        public string MDRCDetailOfCounsellingSessionsSesssionIII { get; set; }
        public string MDRCMSOProvisionReadingMaterial { get; set; }
        public string MDRCIndoorActivities { get; set; }
        public string MDRCRecreationalActivities { get; set; }
        public string MDRCAnyOtherMSO { get; set; }
        public Nullable<int> ReferProvinceID { get; set; }
        public Nullable<int> SessionNo { get; set; }
        public Nullable<bool> isVisitClosed { get; set; }
        public Nullable<int> ReferDivisionID { get; set; }
        public string Education { get; set; }
        public Nullable<int> PtPositionInFamily { get; set; }
        public Nullable<int> NoOfSisters { get; set; }
        public Nullable<int> NoOfBrothers { get; set; }
    }
}
