//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRReports.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpeechAndLanguageHistory
    {
        public System.Guid SpeechAndLanguageHistoryId { get; set; }
        public Nullable<System.Guid> PatientId { get; set; }
        public Nullable<System.Guid> PatientVisitId { get; set; }
        public Nullable<System.Guid> PatientDiagnoseId { get; set; }
        public string MotherLanguage { get; set; }
        public string LanguageSpokenAtHome { get; set; }
        public string LanguageSpokenAtSchool { get; set; }
        public string ChildCommunicates { get; set; }
        public string LanguageProblem { get; set; }
        public string ChildVisitProfessional { get; set; }
        public string ChildInteraction { get; set; }
        public string OtherBehavioralProblem { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<System.Guid> UpdatedBy { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public Nullable<System.Guid> DeletedBy { get; set; }
        public Nullable<byte> ActionTypeId { get; set; }
    }
}
