//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRReports.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpeechTherapyPatientAssessment
    {
        public System.Guid SpeechTherapyPatientAssessmentId { get; set; }
        public Nullable<System.Guid> PatientId { get; set; }
        public Nullable<System.Guid> PatientVisitId { get; set; }
        public Nullable<System.Guid> PatientDiagnoseId { get; set; }
        public string ConversationSpeech { get; set; }
        public string ConsistencySoundError { get; set; }
        public Nullable<int> PattersSoundError { get; set; }
        public string StimulabilitySoundError { get; set; }
        public string ReceptiveLanguage { get; set; }
        public string ExpressiveLanguage { get; set; }
        public Nullable<int> Cognition { get; set; }
        public string RelevantMedicalhistorySwallowing { get; set; }
        public Nullable<int> CurrentFeedingStatus { get; set; }
        public Nullable<int> Dietarylimitations { get; set; }
        public Nullable<int> CognitiveStatus { get; set; }
        public string SignificantOralMotorFinding { get; set; }
        public string TypeOfdysfluency { get; set; }
        public string AssociatedMotorBehavior { get; set; }
        public string AvoidanceOfSounds { get; set; }
        public string StimulabilityOfFluentSpeech { get; set; }
        public string ChildVoiceQuality { get; set; }
        public string ChildVoicePitch { get; set; }
        public string ChildVoiceResonance { get; set; }
        public string StimulabilityOfImprovedVoice { get; set; }
        public string OralFacialExaminationFindings { get; set; }
        public string Voiceimprovement { get; set; }
        public string PreviousInterventionTherapy { get; set; }
        public string PlanOfCare { get; set; }
        public string ScheduleOfTherapyCarePlan { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<System.Guid> UpdatedBy { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public Nullable<System.Guid> DeletedBy { get; set; }
        public Nullable<byte> ActionTypeId { get; set; }
    }
}
