//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRReports.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SyncToOfflineErrorLog
    {
        public long SyncToOfflineErrorLogId { get; set; }
        public Nullable<bool> Response { get; set; }
        public string Json { get; set; }
        public string ErrorNumber { get; set; }
        public string ErrorSeverity { get; set; }
        public string ErrorState { get; set; }
        public string ErrorMethod { get; set; }
        public string ErrorLine { get; set; }
        public string ErrorMessage { get; set; }
        public Nullable<System.DateTime> ReportedOn { get; set; }
    }
}
