//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRReports.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRegistrationLog
    {
        public System.Guid UserId { get; set; }
        public Nullable<int> ProvinceId { get; set; }
        public Nullable<int> DivisionId { get; set; }
        public Nullable<int> DistrictId { get; set; }
        public Nullable<int> TehsilId { get; set; }
        public Nullable<int> UcId { get; set; }
        public string FullName { get; set; }
        public string FatherName { get; set; }
        public string Username { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string ContactNo { get; set; }
        public string ProfilePic { get; set; }
        public string CNIC { get; set; }
        public Nullable<int> HrId { get; set; }
        public Nullable<int> HealthFacilityId { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<int> SectionId { get; set; }
        public string CurrentGradeBPS { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<System.Guid> GenderProfileId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.Guid> DesignationProfileId { get; set; }
        public Nullable<System.Guid> UserTypeProfileId { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.Guid> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<System.Guid> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
        public Nullable<long> UserLogId { get; set; }
        public byte ActionTypeId { get; set; }
        public Nullable<System.DateTime> ActionDate { get; set; }
        public Nullable<bool> PmisUSER { get; set; }
        public Nullable<bool> IsShowRoleOnly { get; set; }
        public Nullable<bool> IsUserLoginFirstTime { get; set; }
        public Nullable<System.DateTime> PasswordChangedOn { get; set; }
    }
}
