//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRReports.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewIPDPatientVisit
    {
        public System.Guid PatientId { get; set; }
        public System.Guid PatientVisitId { get; set; }
        public System.Guid PatientDiagnoseId { get; set; }
        public string FullName { get; set; }
        public string CNIC { get; set; }
        public string MobileNo { get; set; }
        public string MRNo { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<System.DateTime> PatientAdmittedOn { get; set; }
        public Nullable<System.DateTime> DateOfDischarge { get; set; }
        public Nullable<System.Guid> PatientVitalId { get; set; }
        public string BPSystolic { get; set; }
        public string BPDiaSystolic { get; set; }
        public string Pulse { get; set; }
        public string Temprature { get; set; }
        public string Weight { get; set; }
        public string Height { get; set; }
        public string ResperatoryRate { get; set; }
        public Nullable<System.DateTime> Vital_Collection_Date { get; set; }
        public Nullable<System.Guid> PatientPrescriptionId { get; set; }
        public string MedicineName { get; set; }
        public string MedicineDose { get; set; }
        public string MedicineFrequency { get; set; }
        public string MedicineInstruction { get; set; }
        public string MedicineDuration { get; set; }
        public Nullable<System.DateTime> Medicine_Prescribe_Date { get; set; }
        public Nullable<int> LabTestId { get; set; }
        public Nullable<System.Guid> PatientLabTestId { get; set; }
        public string LabTestName { get; set; }
        public Nullable<System.DateTime> Lab_Test_Advise_Date { get; set; }
    }
}
