//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRReports.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewAnmonalTestDetail
    {
        public Nullable<System.Guid> PatientVisitId { get; set; }
        public System.Guid PatientLabTestId { get; set; }
        public string SectionName { get; set; }
        public int SectionLookupId { get; set; }
        public string TestName { get; set; }
        public decimal Price { get; set; }
        public string TestTypeShortName { get; set; }
        public bool PaidStatus { get; set; }
        public bool IsAdvisedExternally { get; set; }
        public string LabDepartmentShortName { get; set; }
        public string LabDepartmentName { get; set; }
        public Nullable<decimal> DiscountInPercentage { get; set; }
        public Nullable<decimal> DiscountedPrice { get; set; }
        public Nullable<System.Guid> DiscountedByProfileId { get; set; }
        public string DiscountedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public string Designation { get; set; }
        public Nullable<int> IsDiscountedByDoctor { get; set; }
    }
}
