//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRReports.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewPatientVitalList
    {
        public int ProvinceId { get; set; }
        public string ProvinceName { get; set; }
        public int DivisionId { get; set; }
        public string DivisionName { get; set; }
        public int DistrictId { get; set; }
        public string DistrictName { get; set; }
        public int TehsilId { get; set; }
        public string TehsilName { get; set; }
        public int HealthFacilityId { get; set; }
        public string HealthFacilityName { get; set; }
        public System.Guid PatientVisitId { get; set; }
        public Nullable<System.Guid> PatientId { get; set; }
        public System.Guid PatientVitalId { get; set; }
        public Nullable<System.DateTime> VisitDate { get; set; }
        public string PatientName { get; set; }
        public string PatientMobileNo { get; set; }
        public string MRNo { get; set; }
        public string CNIC { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public string CreatedByName { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.Guid> UpdatedBy { get; set; }
        public string UpdatedByName { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> DepartementLookupId { get; set; }
        public Nullable<int> SectionLookupId { get; set; }
        public int PatientProvinceId { get; set; }
        public string Weight { get; set; }
        public Nullable<System.Guid> GenderId { get; set; }
        public string ResperatoryRate { get; set; }
        public string Temprature { get; set; }
        public string Pulse { get; set; }
        public string BPDiaSystolic { get; set; }
        public string BPSystolic { get; set; }
        public string Height { get; set; }
        public string CurrentStation { get; set; }
    }
}
