//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRReports.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewGetPatientLabTestList
    {
        public Nullable<System.Guid> PatientId { get; set; }
        public Nullable<System.Guid> PatientVisitId { get; set; }
        public Nullable<System.Guid> PatientDiagnoseId { get; set; }
        public Nullable<int> LabTestId { get; set; }
        public System.Guid PatientLabTestId { get; set; }
        public string Name { get; set; }
        public string DepartmentName { get; set; }
        public Nullable<System.Guid> DepartmentProfileId { get; set; }
        public string DepartmentShortName { get; set; }
        public Nullable<System.Guid> PrescribedBy { get; set; }
        public string PrescribedByName { get; set; }
        public string FormType { get; set; }
        public string PrescribedByDesignation { get; set; }
        public Nullable<System.DateTime> PrescribedOn { get; set; }
        public Nullable<int> TestPrice { get; set; }
        public string Status { get; set; }
        public Nullable<bool> IsReportGenerated { get; set; }
    }
}
