//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRReports.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewPatientLabTestDetail
    {
        public string FullName { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public Nullable<System.DateTime> VisitDate { get; set; }
        public string Gender { get; set; }
        public string VisitHF { get; set; }
        public string PatientHF { get; set; }
        public string Relation { get; set; }
        public string PatientDivisionName { get; set; }
        public string PatientProvinceName { get; set; }
        public string PatientDistrictName { get; set; }
        public string PatientTehsilName { get; set; }
        public Nullable<System.DateTime> PatientCreatedOn { get; set; }
        public Nullable<System.DateTime> PatientVisitCreatedOn { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> HealthFacilityProvinceId { get; set; }
        public Nullable<int> HealthFacilityDivisionId { get; set; }
        public Nullable<int> HealthFacilityDistrictId { get; set; }
        public Nullable<int> HealthFacilityTehsilId { get; set; }
        public int HealthFacilityId { get; set; }
        public Nullable<int> LabTestId { get; set; }
        public Nullable<System.Guid> PatientId { get; set; }
        public Nullable<int> DepartementLookupId { get; set; }
        public Nullable<int> SectionLookupId { get; set; }
        public string PatientVisitCreatedByName { get; set; }
        public string LabTestName { get; set; }
        public Nullable<System.Guid> PatientLabTestCreatedBy { get; set; }
        public string ReportGeneratedByName { get; set; }
        public Nullable<System.Guid> ReportGeneratedBy { get; set; }
        public string Department { get; set; }
        public Nullable<bool> IsSampleCollected { get; set; }
        public Nullable<bool> IsReportGenerated { get; set; }
        public Nullable<System.Guid> SampleCollectedBy { get; set; }
        public string LabType { get; set; }
        public string SampleCollectedByName { get; set; }
    }
}
