//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRReports.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewPatientOpenVisit
    {
        public string FullName { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string CNIC { get; set; }
        public string Domicile { get; set; }
        public string Email { get; set; }
        public string GuardianName { get; set; }
        public Nullable<int> HealthFacilityId { get; set; }
        public Nullable<System.DateTime> VisitDate { get; set; }
        public string Name { get; set; }
    }
}
