//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRReports.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewSpecialityRoomNo
    {
        public int HfDepartmentId { get; set; }
        public Nullable<int> DepartmentLookupId { get; set; }
        public Nullable<int> SectionLookupId { get; set; }
        public Nullable<int> HealthFacilityId { get; set; }
        public string VitalsFloorNo { get; set; }
        public string VitalsRoomNo { get; set; }
        public string DoctorFloorNo { get; set; }
        public string DoctorRoomNo { get; set; }
        public string PharmacyFloorNo { get; set; }
        public string PharmacyRoomNo { get; set; }
        public string PathalogyFloorNo { get; set; }
        public string PathalogyRoomNo { get; set; }
        public string AlmonerFloorNo { get; set; }
        public string AlmonerRoomNo { get; set; }
    }
}
