//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRReports.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewSocialWellfareDeputyDirector
    {
        public System.Guid PatientId { get; set; }
        public string FullName { get; set; }
        public string Gender { get; set; }
        public System.Guid SocialWellfareFormId { get; set; }
        public Nullable<bool> IsDrugAddict { get; set; }
        public string CNIC { get; set; }
        public string MRNo { get; set; }
        public string LastName { get; set; }
        public Nullable<decimal> Age { get; set; }
        public Nullable<System.Guid> PatientVistId { get; set; }
        public string MobileNo { get; set; }
        public int PatientDistrctId { get; set; }
        public string PatientDivisionName { get; set; }
        public int PatientDivisionId { get; set; }
        public Nullable<System.DateTime> VisitDate { get; set; }
        public int HealthFacilityId { get; set; }
        public string VisitHF { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public int TehsilId { get; set; }
        public string PatientDistrictName { get; set; }
        public Nullable<bool> isAssignDoctor { get; set; }
        public Nullable<int> DivisionId { get; set; }
        public Nullable<int> DistrictId { get; set; }
        public Nullable<int> ReferDistrictId { get; set; }
        public Nullable<bool> isVisitClosed { get; set; }
        public string AssignedDoctor { get; set; }
        public Nullable<System.Guid> DoctorId { get; set; }
        public Nullable<int> SessionNo { get; set; }
        public string PtStatus { get; set; }
    }
}
