//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRReports.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewGetAccumulateMedicineDispatch
    {
        public int MedicineId { get; set; }
        public string MedicineName { get; set; }
        public Nullable<int> QuantityDispatched { get; set; }
        public Nullable<int> WardId { get; set; }
        public string HealthFacilityCode { get; set; }
        public Nullable<int> HealthFacilityHrId { get; set; }
        public Nullable<int> HealthFacilityId { get; set; }
        public Nullable<bool> MIMSDispatched { get; set; }
    }
}
