//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRReports.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewPatientOpenVisitCountByDeptBySecByMonth
    {
        public string DepartmentName { get; set; }
        public int DepartmentId { get; set; }
        public string SectionName { get; set; }
        public int SectionId { get; set; }
        public Nullable<int> VisitCount { get; set; }
        public Nullable<int> HealthFacilityId { get; set; }
        public Nullable<int> VisitMonth { get; set; }
    }
}
