//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRReports.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewLabTestResults
    {
        public System.Guid PatientLabTestId { get; set; }
        public int VisitNo { get; set; }
        public string FullName { get; set; }
        public string MRNo { get; set; }
        public string CNIC { get; set; }
        public string MobileNo { get; set; }
        public int ProvinceId { get; set; }
        public int DivisionId { get; set; }
        public string DivisionCode { get; set; }
        public string DivisionName { get; set; }
        public int DistrictId { get; set; }
        public string DistrictCode { get; set; }
        public string DistrictName { get; set; }
        public int TehsilId { get; set; }
        public string TehsilCode { get; set; }
        public string TehsilName { get; set; }
        public int HealthFacilityId { get; set; }
        public string HealthFacilityName { get; set; }
        public Nullable<int> DepartementLookupId { get; set; }
        public Nullable<int> SectionLookupId { get; set; }
        public string FormType { get; set; }
        public string TestName { get; set; }
        public string TestResultName { get; set; }
        public string Result { get; set; }
        public Nullable<bool> IsSampleCollected { get; set; }
        public Nullable<bool> IsSampleRejected { get; set; }
        public Nullable<bool> IsReportGenerated { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public byte ActionTypeId { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
