//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRReports.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewPatientOpenVisitDetail
    {
        public string FullName { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public Nullable<System.DateTime> VisitDate { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<decimal> Age { get; set; }
        public string Gender { get; set; }
        public Nullable<int> ChartPieSequenceNo { get; set; }
        public System.Guid GenderId { get; set; }
        public string VisitHF { get; set; }
        public string PatientHF { get; set; }
        public string Relation { get; set; }
        public string PatientDivisionName { get; set; }
        public string PatientProvinceName { get; set; }
        public string PatientDistrictName { get; set; }
        public string PatientTehsilName { get; set; }
        public Nullable<System.DateTime> PatientCreatedOn { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> HealthFacilityProvinceId { get; set; }
        public Nullable<int> HealthFacilityDivisionId { get; set; }
        public Nullable<int> HealthFacilityDistrictId { get; set; }
        public Nullable<int> HealthFacilityTehsilId { get; set; }
        public int HealthFacilityId { get; set; }
        public Nullable<System.Guid> PatientVisitCreatedBy { get; set; }
        public string Cnic { get; set; }
        public string MobileNo { get; set; }
        public string MRNo { get; set; }
        public System.Guid PatientId { get; set; }
        public System.Guid PatientOpenVisitId { get; set; }
        public Nullable<int> DepartementLookupId { get; set; }
        public Nullable<int> SectionLookupId { get; set; }
        public string PatientVisitCreatedByName { get; set; }
        public string PatientVisitCreatedByCnic { get; set; }
        public string PatientVisitCreatedByDesignation { get; set; }
        public int PatientProvinceId { get; set; }
        public bool IsFromPMIS { get; set; }
        public Nullable<bool> IsVisitClosed { get; set; }
        public Nullable<bool> IsFilterClinic { get; set; }
        public Nullable<int> ConsultantSectionLookupId { get; set; }
        public Nullable<bool> IsConsultant { get; set; }
        public string SectionName { get; set; }
        public string CurrentStation { get; set; }
        public Nullable<int> VisitNo { get; set; }
        public Nullable<bool> IsSscClaimed { get; set; }
        public Nullable<bool> IsEligibleForSsc { get; set; }
        public Nullable<System.Guid> ReasonIfNotEligibleForSsc { get; set; }
        public Nullable<System.Guid> ReasonIfSscNotClaimed { get; set; }
    }
}
