//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRReports.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewDrugAddictCommunityDevelopment
    {
        public string FullName { get; set; }
        public string CNIC { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string MRNo { get; set; }
        public string Gender { get; set; }
        public System.Guid PatientVisitId { get; set; }
        public Nullable<System.DateTime> VisitDate { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string RelationWithPt { get; set; }
        public string PtMedicineRoutine { get; set; }
        public string PtDoctorCheckup { get; set; }
        public string PtDailyRoutine { get; set; }
        public string PtFamilyAttitude { get; set; }
        public string CounsellingOfPatientOrFamily { get; set; }
        public string GuidanceProvided { get; set; }
        public string PtStatus { get; set; }
        public System.Guid DoctorId { get; set; }
        public string PhoneNo { get; set; }
        public Nullable<int> SessionNo { get; set; }
        public string HomeVisited { get; set; }
        public string PtTelephoneOrHomeVisited { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public string DoctorName { get; set; }
        public string PatientDistrictName { get; set; }
    }
}
