//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRReports.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewTBLabTest
    {
        public int LabTestId { get; set; }
        public Nullable<System.Guid> PatientVisitId { get; set; }
        public string Name { get; set; }
        public string TestName { get; set; }
        public string Result { get; set; }
    }
}
