//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRReports.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewSocialWellfarePatientDetail
    {
        public System.Guid SocialWelfareFormId { get; set; }
        public Nullable<System.Guid> PatientVistId { get; set; }
        public Nullable<int> ReferDistrictId { get; set; }
        public string MDRCIndoorActivities { get; set; }
        public Nullable<int> ReferDivisionID { get; set; }
        public string FullName { get; set; }
        public Nullable<bool> isVisitClosed { get; set; }
        public string MDRCProfession { get; set; }
        public string MDRCMonthlyIncome { get; set; }
        public string MDRCFHRDrugAddiction { get; set; }
        public string MDRCIfYesRelation { get; set; }
        public string MDRCFamilyAttitude { get; set; }
        public string MDRCPatientAttitude { get; set; }
        public Nullable<int> SessionNo { get; set; }
        public string MDRCMSOProvisionReadingMaterial { get; set; }
        public string MDRCRecreationalActivities { get; set; }
        public string Education { get; set; }
        public Nullable<int> NoOfSisters { get; set; }
        public Nullable<int> NoOfBrothers { get; set; }
        public Nullable<int> PtPositionInFamily { get; set; }
        public string MDRCAnyOtherMSO { get; set; }
        public string MobileNo { get; set; }
        public string MRNo { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string CNIC { get; set; }
        public string MDRCDetailOfCounsellingSessionsSesssionI { get; set; }
        public string FamilyCounsellingSessions { get; set; }
        public Nullable<System.DateTime> VisitDate { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<decimal> Age { get; set; }
        public string Gender { get; set; }
        public string VisitHF { get; set; }
        public string PatientHF { get; set; }
        public string Relation { get; set; }
        public string PatientDivisionName { get; set; }
        public int PatientDivisionId { get; set; }
        public string PatientProvinceName { get; set; }
        public string PatientDistrictName { get; set; }
        public int PatientDistrctId { get; set; }
        public string PatientTehsilName { get; set; }
        public Nullable<System.DateTime> PatientCreatedOn { get; set; }
        public Nullable<System.DateTime> PatientVisitCreatedOn { get; set; }
        public Nullable<int> HealthFacilityProvinceId { get; set; }
        public Nullable<int> HealthFacilityDivisionId { get; set; }
        public Nullable<int> HealthFacilityDistrictId { get; set; }
        public Nullable<int> HealthFacilityTehsilId { get; set; }
        public int HealthFacilityId { get; set; }
        public Nullable<int> DepartementLookupId { get; set; }
        public Nullable<int> SectionLookupId { get; set; }
        public string PatientVisitCreatedByName { get; set; }
        public byte ActionTypeId { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    }
}
