//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRReports.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewGetCreateRoleMenuAccess
    {
        public Nullable<System.Guid> RoleMenuId { get; set; }
        public Nullable<System.Guid> RoleId { get; set; }
        public System.Guid MenuId { get; set; }
        public Nullable<bool> IsModule { get; set; }
        public Nullable<System.Guid> ModuleId { get; set; }
        public string Name { get; set; }
        public string DisplayName { get; set; }
        public Nullable<int> SeqNo { get; set; }
        public Nullable<System.Guid> ParentId { get; set; }
        public Nullable<bool> HasAccess { get; set; }
        public Nullable<bool> CanWrite { get; set; }
        public Nullable<bool> CanRead { get; set; }
        public Nullable<bool> CanEdit { get; set; }
        public Nullable<bool> CanDelete { get; set; }
    }
}
