//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRReports.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewDrugAddictsPatientVisits
    {
        public System.Guid PatientId { get; set; }
        public System.Guid PatientOpenVisitId { get; set; }
        public string FullName { get; set; }
        public string CNIC { get; set; }
        public string Addicted { get; set; }
        public string GuardianName { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Gender { get; set; }
        public string ParmanentAddress { get; set; }
        public string District { get; set; }
        public Nullable<System.DateTime> AdmissionDate { get; set; }
        public Nullable<System.DateTime> DischargeDate { get; set; }
        public int HealthFacilityId { get; set; }
        public string TreatmentStatus { get; set; }
        public string REHABILITATION { get; set; }
        public Nullable<int> HealthFacilityTypeId { get; set; }
        public string Name { get; set; }
        public string HealthFacility { get; set; }
        public string Json { get; set; }
    }
}
