//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRReports.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewHealthFacilityDepartmentList
    {
        public int HfDepartmentId { get; set; }
        public int ProvinceId { get; set; }
        public int DivisionId { get; set; }
        public int DistrictId { get; set; }
        public int TehsilId { get; set; }
        public Nullable<int> HealthFacilityId { get; set; }
        public string HealthFacilityName { get; set; }
        public Nullable<int> DepartmentLookupId { get; set; }
        public string DepartmentName { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public string CreatedByName { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.Guid> UpdatedBy { get; set; }
        public string UpdatedByName { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public bool IsActive { get; set; }
    }
}
