//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRReports.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewAnmonalList
    {
        public Nullable<System.Guid> PatientVisitId { get; set; }
        public Nullable<System.Guid> PatientId { get; set; }
        public string CNIC { get; set; }
        public string MobileNo { get; set; }
        public string PatientName { get; set; }
        public string LabDepartmentShortName { get; set; }
        public string LabDepartmentName { get; set; }
        public bool IsPaid { get; set; }
        public Nullable<System.Guid> PaymentReceivedBy { get; set; }
        public Nullable<System.DateTime> PaymentReceivedOn { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    }
}
