//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRReports.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewTbPatientsList
    {
        public System.Guid PatientId { get; set; }
        public string MRNo { get; set; }
        public string FullName { get; set; }
        public string CNIC { get; set; }
        public Nullable<int> Age { get; set; }
        public string MobileNo { get; set; }
        public string FormType { get; set; }
        public Nullable<int> DepartementLookupId { get; set; }
        public Nullable<int> SectionLookupId { get; set; }
        public Nullable<System.Guid> GenderId { get; set; }
        public Nullable<int> ProvinceId { get; set; }
        public Nullable<int> DivisionId { get; set; }
        public Nullable<int> DistrictId { get; set; }
        public int TehsilId { get; set; }
        public Nullable<int> HealthFacilityId { get; set; }
        public Nullable<System.Guid> CreatedById { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
    }
}
