//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRReports.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class viewTBIssuedMedicine
    {
        public System.Guid PatientVisitId { get; set; }
        public string FullName { get; set; }
        public string CNIC { get; set; }
        public string MobileNo { get; set; }
        public string MRNo { get; set; }
        public int ProvinceId { get; set; }
        public int DivisionId { get; set; }
        public string DivisionName { get; set; }
        public int DistrictId { get; set; }
        public string DistrictName { get; set; }
        public int TehsilId { get; set; }
        public string TehsilName { get; set; }
        public Nullable<int> DepartementLookupId { get; set; }
        public Nullable<int> SectionLookupId { get; set; }
        public int HealthFacilityId { get; set; }
        public string HealthFacilityName { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    }
}
