//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRReports.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewGetAllMedicineAdvisedRequisition
    {
        public System.Guid MedicineAdvisedRequisitionId { get; set; }
        public System.Guid PatientId { get; set; }
        public Nullable<System.Guid> PatientDiagnoseId { get; set; }
        public System.Guid PatientVisitId { get; set; }
        public string RequsitionBy { get; set; }
        public string RequsitionFor { get; set; }
        public Nullable<System.DateTime> RequsitionOn { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public string Status { get; set; }
        public bool IsActive { get; set; }
        public byte ActionTypeId { get; set; }
    }
}
