using System;
using System.Collections.Generic;

namespace AuthDAL.Models.DbModelsReporting;

public partial class PatientDiagnose
{
    public Guid PatientDiagnoseId { get; set; }

    public Guid? PatientId { get; set; }

    public Guid? PatientVisitId { get; set; }

    public Guid? OutcomeStatusProfileId { get; set; }

    public string? FormType { get; set; }

    public string? PresentComplaints { get; set; }

    public string? Examination { get; set; }

    public string? PatientMedicalHistory { get; set; }

    public string? AdviseGiven { get; set; }

    public DateTime? FollowupDate { get; set; }

    public int DoctorVisitNo { get; set; }

    public int? DocDepartmentLookupId { get; set; }

    public int? DocSectionLookupId { get; set; }

    public Guid? DiagnosedBy { get; set; }

    public bool? IsDiagnoseExternally { get; set; }

    public string? SourceDoctorName { get; set; }

    public bool IsActive { get; set; }

    public bool? IsConfirmed { get; set; }

    public DateTime? CreatedOn { get; set; }

    public Guid? CreatedBy { get; set; }

    public DateTime? UpdatedOn { get; set; }

    public Guid? UpdatedBy { get; set; }

    public DateTime? DeletedOn { get; set; }

    public Guid? DeletedBy { get; set; }

    public long? UserLogId { get; set; }

    public byte ActionTypeId { get; set; }

    public bool? IsVerifiedByConsultant { get; set; }

    public Guid? MedicineResourceProfileId { get; set; }

    public bool? IsAutoGenerated { get; set; }

    public bool? IsMlc { get; set; }

    public bool? IsFromCallCenter { get; set; }

    public Guid? SourceSystemId { get; set; }

    public bool? IsSendToCdc { get; set; }

    public Guid? MedicineRegimeProfileId { get; set; }

    public bool? AnyMedicineReaction { get; set; }

    public string? ReactionNote { get; set; }

    public bool? IsDischargeDiagnose { get; set; }

    public int? PatientVisitCount { get; set; }

    public Guid? PatientVisitTypeProfileId { get; set; }

    public Guid? SvrStatusProfileId { get; set; }

    public Guid? PcrStatusProfileId { get; set; }

    public Guid? FollowupDateTypeProfileId { get; set; }

    public int? ReferToDepartmentLookupId { get; set; }

    public int? ReferToSectionLookupId { get; set; }

    public bool? IsRefer { get; set; }
}
