<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\ApplicationCore\Common\AppCommonMethods\AppCommonMethods.csproj" />
    <ProjectReference Include="..\..\..\ApplicationCore\Common\JWTAuthentication\JWTAuthentication.csproj" />
    <ProjectReference Include="..\..\..\ApplicationCore\Common\RedisCache\RedisCache\RedisCache.csproj" />
    <ProjectReference Include="..\..\..\ApplicationCore\Common\SMSSender\SMSSender.csproj" />
    <ProjectReference Include="..\..\Auth\BAL\AuthBAL\AuthBAL.csproj" />
    <ProjectReference Include="..\HMIS.Patient.Domain\HMIS.Patient.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="DPCtlUruNet">
      <HintPath>C:\Program Files\DigitalPersona\U.are.U SDK\Windows\Lib\.NET\DPCtlUruNet.dll</HintPath>
    </Reference>
    <Reference Include="DPCtlXUru">
      <HintPath>C:\Program Files\DigitalPersona\U.are.U SDK\Windows\Lib\.NET\DPCtlXUru.dll</HintPath>
    </Reference>
    <Reference Include="DPUruNet">
      <HintPath>C:\Program Files\DigitalPersona\U.are.U SDK\Windows\Lib\.NET\DPUruNet.dll</HintPath>
    </Reference>
    <Reference Include="DPXUru">
      <HintPath>C:\Program Files\DigitalPersona\U.are.U SDK\Windows\Lib\.NET\DPXUru.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>
