using AppCommonMethods;
using AutoMapper;
using CommonDTOs.Enums;
using CommonExceptionHandler;
using CommonMessages;
using HMIS.Patient.Domain.Models.DbModels;
using HMIS.Patient.Domain.Models.DTO.MedicineAdvisedDto;
using HMIS.Patient.Domain.Models.DTO.MedicineAdvisedRequisitionDto;
using HMIS.Patient.Domain.Models.DTO.NursingEventDto;
using HMIS.Patient.Domain.Models.DTO.PatientPrescriptionDto;
using HMIS.Patient.Domain.Repositories.UOW;
using JWTAuthentication;
using Microsoft.EntityFrameworkCore;

namespace HMIS.Patient.Service
{
    public class MedicineAdvisedService
    {
        #region Class Fields & Propertities

        private readonly TokenService _tokenService;
        private readonly IMapper _mapper;
        private readonly UnitOfWork<MedicineAdvised> _uowMedicineAdvised;
        private readonly MedicineAdvisedRequisitionService<MedicineAdvisedRequisition> _medicineAdvisedRequisitionService;
        private readonly NursingEventsService<NursingEvent> _nursingEventsService;

        #endregion

        #region Constructor

        public MedicineAdvisedService(
            TokenService tokenService,
            UnitOfWork<MedicineAdvised> uowMedicineAdvised,
            IMapper mapper,
            MedicineAdvisedRequisitionService<MedicineAdvisedRequisition> medicineAdvisedRequisitionService,
            NursingEventsService<NursingEvent> nursingEventsService
        )
        {
            _tokenService = tokenService;
            _mapper = mapper;
            _uowMedicineAdvised = uowMedicineAdvised;
            _medicineAdvisedRequisitionService = medicineAdvisedRequisitionService;
            _nursingEventsService = nursingEventsService;
        }

        #endregion

        #region CUD Operations

        public async Task<CreateOrEditMedicineAdvisedDto> CreateOrEdit(CreateOrEditMedicineAdvisedDto input)
        {
            if (AppCommonMethod.IsNullOrEmptyGuid(input.MedicineAdvisedId))
                return await Create(input);
            else
                return await Update(input);
        }

        private async Task<CreateOrEditMedicineAdvisedDto> Create(CreateOrEditMedicineAdvisedDto input)
        {
            input.MedicineStartDateTime = DateTime.Now;
            var obj = _mapper.Map<MedicineAdvised>(input);
            FillEntity(obj);
            MedicineAdvised responseObj = await _uowMedicineAdvised.Repository.Insert(obj);
            await _uowMedicineAdvised.Save();

            if (!input.IsRequisition)
            {
                CreateOrEditMedicineAdvisedRequisitionDto objRequisition = new CreateOrEditMedicineAdvisedRequisitionDto();
                objRequisition.PatientId = input.PatientId;
                objRequisition.PatientDiagnoseId = input.PatientDiagnoseId;
                objRequisition.PatientOpenVisitId = input.PatientVisitId;
                objRequisition.IsAutoGenerated = true;
                objRequisition.IsActive = true;

                objRequisition.PatientPrescriptions.Add(new CreateOrEditPatientPrescriptionDto()
                {
                    MedicineAdvisedId = responseObj.MedicineAdvisedId,
                    PatientId = input.PatientId,
                    PatientDiagnoseId = input.PatientDiagnoseId,
                    PatientVisitId= input.PatientVisitId,
                    MedicineId = input.MedicineId,
                    MedicineName = input.MedicineName,
                    BatchNo = input.BatchNo,
                    UnitPrice = input.UnitPrice,
                    Days = input.Days,
                    MedicineDose    = input.MedicineDose,
                    MedicineInstruction = input.MedicineInstruction,
                    MedicineRoute = input.MedicineRoute,
                    MedicineFrequency = input.MedicineFrequency,
                    MedicineDuration = input.MedicineDuration,
                    QuantityPrescribed = input.QuantityPrescribed,

                    AvailableQuantity = input.AvailableQuantity,
                    Quantity = input.QuantityPrescribed ?? 0 - input.AvailableQuantity ?? 0,

                    IsSMLMedicine = input.IsSMLMedicine,
                });
                await _medicineAdvisedRequisitionService.AutoRequisition(objRequisition);
            }


            CreateOrEditNursingEventDto objNursingEvents = new CreateOrEditNursingEventDto();

            objNursingEvents.PatientId = input.PatientId;
            objNursingEvents.PatientDiagnoseId = input.PatientDiagnoseId;
            objNursingEvents.PatientVisitId = input.PatientVisitId;
            objNursingEvents.Events = CommonPrases.MedicineAdvised;

            await _nursingEventsService.CreateEvent(objNursingEvents);




            return _mapper.Map<CreateOrEditMedicineAdvisedDto>(responseObj);

        }

        private async Task<CreateOrEditMedicineAdvisedDto> Update(CreateOrEditMedicineAdvisedDto input)
        {
            var dbObj = await _uowMedicineAdvised.Repository.GetById(input.MedicineAdvisedId!);

            if (AppCommonMethod.IsNullObject(dbObj))
                throw new UserFriendlyException(CommonMessageConstant.RecordNotFound);

            var obj = _mapper.Map(input, dbObj);
            FillEntity(obj!);
            _uowMedicineAdvised.Repository.Update(obj!);
            await _uowMedicineAdvised.CommitAsync();
            return _mapper.Map<CreateOrEditMedicineAdvisedDto>(obj);
        }

        public async Task<bool> Delete(object Id)
        {
            var dbObj = await _uowMedicineAdvised.Repository.GetById(Id);

            if (AppCommonMethod.IsNullObject(dbObj))
                throw new UserFriendlyException(CommonMessageConstant.RecordNotFound);

            FillEntityDelete(dbObj!);

            _uowMedicineAdvised.Repository.Update(dbObj!);
            await _uowMedicineAdvised.CommitAsync();
            return true;
        }

        public async Task<CreateOrEditMedicineAdvisedDto> DiscontinueMedicineAdvised(CreateOrEditMedicineAdvisedDto input)
        {
            var dbObj = await _uowMedicineAdvised.Repository.GetById(input.MedicineAdvisedId!);

            if (AppCommonMethod.IsNullObject(dbObj))
                throw new UserFriendlyException(CommonMessageConstant.RecordNotFound);

            dbObj!.IsDiscontinue = input.IsDiscontinue;

            if (dbObj.IsDiscontinue)
                dbObj.DiscontinueDateTime = DateTime.Now;
            else
            {
                dbObj.DiscontinueDateTime = null;
                dbObj.MedicineStartDateTime = DateTime.Now;
            }

            //var obj = _mapper.Map(input, dbObj);
            FillEntity(dbObj!);
            _uowMedicineAdvised.Repository.Update(dbObj!);
            await _uowMedicineAdvised.CommitAsync();
            return _mapper.Map<CreateOrEditMedicineAdvisedDto>(dbObj);
        }

        public async Task<CreateOrEditMedicineAdvisedDto> UpdateMedicineAdvisedDays(CreateOrEditMedicineAdvisedDto input)
        {
            var dbObj = await _uowMedicineAdvised.Repository.GetById(input.MedicineAdvisedId!);

            if (AppCommonMethod.IsNullObject(dbObj))
                throw new UserFriendlyException(CommonMessageConstant.RecordNotFound);

            dbObj!.IsDiscontinue = input.IsDiscontinue;
            dbObj.Days = input.Days;
            dbObj.MedicineDuration = input.MedicineDuration;

            if (dbObj.IsDiscontinue)
            {
                dbObj.DiscontinueDateTime = DateTime.Now;
                dbObj.QuantityDispatch = null;
                dbObj.QuantityRequisition = null;
            }
            else
            {
                dbObj.QuantityDispatch = null;
                dbObj.QuantityRequisition = null;
                dbObj.DiscontinueDateTime = null;
                dbObj.MedicineStartDateTime = DateTime.Now;
            }

            FillEntity(dbObj!);
            _uowMedicineAdvised.Repository.Update(dbObj!);
            await _uowMedicineAdvised.CommitAsync();
            return _mapper.Map<CreateOrEditMedicineAdvisedDto>(dbObj);
        }

        #endregion

        #region Read Operations

        public async Task<List<ViewMedicineAdvisedDto>> GetByPatientVisitId(Guid patientVisitId)
        {
            List<MedicineAdvised> responseObj = await _uowMedicineAdvised.Repository.GetALL(x => x.PatientVisitId == patientVisitId && x.IsActive && x.ActionTypeId != (int)ActionTypeEnum.Deleted).ToListAsync();

            var obj = _mapper.Map<List<ViewMedicineAdvisedDto>>(responseObj);

            foreach (var item in obj)
            {
                if (item.QuantityPrescribed <= item.QuantityDispatch)
                {
                    item.IsDispenced = true;
                    item.IsDiscontinue = true;
                }
                else if (item.QuantityPrescribed <= item.QuantityRequisition)
                {
                    item.IsRequested = true;
                }
                else if (item.MedicineStartDateTime!.Value.AddDays(Convert.ToDouble(item!.Days)).Date < DateTime.Now.Date)
                {
                    item.IsDiscontinue = true;
                    item.DiscontinueDateTime = DateTime.Now;
                }
                else if (item.IsDiscontinue == null || item.IsDiscontinue == false)
                {
                    item.IsDiscontinue = false;
                    item.DiscontinueDateTime = null;
                }
            }

            return obj;
        }

        #endregion

        #region Helper Methods

        private void FillEntity(MedicineAdvised obj)
        {
            if (AppCommonMethod.IsNullOrEmptyGuid(obj.MedicineAdvisedId))
            {
                obj.MedicineAdvisedId = Guid.NewGuid();
                obj.CreatedBy = _tokenService.GetUserId();
                obj.CreatedOn = DateTime.Now;
                obj.IsActive = true;
                obj.ActionTypeId = (int)ActionTypeEnum.Create;
            }
            else
            {
                obj.UpdatedBy = _tokenService.GetUserId();
                obj.UpdatedOn = DateTime.Now;
                obj.IsActive = true;
                obj.ActionTypeId = (int)ActionTypeEnum.Edit;
            }
        }

        private void FillEntityDelete(MedicineAdvised obj)
        {
            if (obj != null)
            {
                obj.DeletedBy = _tokenService.GetUserId();
                obj.DeletedOn = DateTime.Now;
                obj.ActionTypeId = (int)ActionTypeEnum.Deleted;
            }
        }

        #endregion
    }
}
