using System.Linq.Expressions;
using AppCommonMethods;
using AutoMapper;
using CommonDTOs.Enums;
using CommonExceptionHandler;
using CommonMessages;
using HMIS.Patient.Domain.Models.DbModels;
using HMIS.Patient.Domain.Models.DTO.PatientOpenVisitDto;
using HMIS.Patient.Domain.Models.DTO.PatientDto;
using HMIS.Patient.Domain.Repositories.UOW;
using JWTAuthentication;
using Microsoft.EntityFrameworkCore;
using DbModel = HMIS.Patient.Domain.Models.DbModels;
using HMIS.Patient.Domain.Models.DTO.PaginationDto;
using System.Linq;
using HMIS.Patient.Domain.Models.DTO.Patient;
using Microsoft.IdentityModel.Tokens;
using CommonDTOs;
using FileHandler;
using HMIS.Patient.Domain.Models.DTO.PatientDocument;
using HMIS.Patient.Domain.Models.DTO.Common;
using HMIS.Patient.Domain.Models.DTO.PatientVisitFlowDto;
using HMIS.Patient.Domain.Models.DTO.PatientWorkFlowLogDto;
using Microsoft.Data.SqlClient;
using System.Data;
using HMIS.Patient.Domain.Models.DTO.PatientDischargeDetailDto;

namespace HMIS.Patient.Service
{
    public class PatientOpenVisitService<TEntity> where TEntity : class
    {
        #region Class Fields & Propertities

        private readonly TokenService _tokenService;
        private readonly IMapper _mapper;
        private readonly UnitOfWork<PatientOpenVisit> _uowPatientOpenVisit;
        private readonly UnitOfWork<PatientDiagnose> _uowPatientDiagnose;
        private readonly PatientDocumentService<PatientDocument> _patientDocumentService;
        private readonly UploadFiles _fileUploader;
        #endregion

        #region Constructor

        public PatientOpenVisitService(TokenService tokenService, UnitOfWork<PatientOpenVisit> uowPatientOpenVisit, IMapper mapper, UnitOfWork<PatientDiagnose> uowPatientDiagnose, PatientDocumentService<PatientDocument> patientDocumentService)
        {
            _tokenService = tokenService;
            _uowPatientOpenVisit = uowPatientOpenVisit;
            _mapper = mapper;
            _uowPatientDiagnose = uowPatientDiagnose;
            _patientDocumentService = patientDocumentService;
            
        }

        #endregion

        #region CUD Operations

        public async Task<CreateOrEditOpenVisitDto> CreateOrEdit(CreateOrEditOpenVisitDto input)
        {
            if (AppCommonMethod.IsNullOrEmptyGuid(input.PatientOpenVisitId))
                return await Create(input);
            else
                return await Update(input);
        }

        private async Task<CreateOrEditOpenVisitDto> Create (CreateOrEditOpenVisitDto input)
        {
            var obj = _mapper.Map<PatientOpenVisit>(input);
            FillEntity(obj);
            input.PatientOpenVisitId = obj.PatientOpenVisitId;
            PatientOpenVisit responseObj = await _uowPatientOpenVisit.Repository.Insert(obj);
            await _uowPatientOpenVisit.CommitAsync();
            return _mapper.Map<CreateOrEditOpenVisitDto>(responseObj);
        }

        private async Task<CreateOrEditOpenVisitDto> Update (CreateOrEditOpenVisitDto input)
        {
            var dbObj = await _uowPatientOpenVisit.Repository.GetById(input.PatientOpenVisitId!);

            if (AppCommonMethod.IsNullObject(dbObj))
                throw new UserFriendlyException(CommonMessageConstant.RecordNotFound);

            var obj = _mapper.Map(input, dbObj);

            FillEntity(obj!);

            _uowPatientOpenVisit.Repository.Update(obj!);
            await _uowPatientOpenVisit.CommitAsync();

            return _mapper.Map<CreateOrEditOpenVisitDto>(obj);

        }

        public async Task<CreateOrEditOpenVisitDto> CreateOrEditAutoVisit(CreateOrEditOpenVisitDto input)
        {
            if (AppCommonMethod.IsNullOrEmptyGuid(input.PatientOpenVisitId))
                return await CreateAutoVisit(input);
            else
                return input;
                //return await Update(input);
        }

        private async Task<CreateOrEditOpenVisitDto> CreateAutoVisit(CreateOrEditOpenVisitDto input)
        {
            var obj = _mapper.Map<PatientOpenVisit>(input);
            FillEntity(obj);
            obj.IsAutoGenerated = true;
            PatientOpenVisit responseObj = await _uowPatientOpenVisit.Repository.Insert(obj);
            await _uowPatientOpenVisit.CommitAsync();
            return _mapper.Map<CreateOrEditOpenVisitDto>(responseObj);
        }

        public async Task<bool> Delete(object Id)
        {
            var dbObj = await _uowPatientOpenVisit.Repository.GetById(Id);

            if (AppCommonMethod.IsNullObject(dbObj))
                throw new UserFriendlyException(CommonMessageConstant.RecordNotFound);

            FillEntityDelete(dbObj!);

            _uowPatientOpenVisit.Repository.Update(dbObj!);
            await _uowPatientOpenVisit.CommitAsync();
            return true;
        }

        public async Task<bool> ReleaseOccupiedPatientVisit(Guid VisitId)
        {
            var dbObj = await _uowPatientOpenVisit.Repository.GetById(VisitId);

            if (AppCommonMethod.IsNullObject(dbObj))
                throw new UserFriendlyException(CommonMessageConstant.RecordNotFound);

            //FillEntityDelete(dbObj!);

            dbObj.IsOccupied = false;
            dbObj.OccupiedBy = null;
            dbObj.AttendedBy = null;

            _uowPatientOpenVisit.Repository.Update(dbObj!);
            await _uowPatientOpenVisit.CommitAsync();
            return true;
        }

        //public async Task<PatientDischargeDto> DischargePatientVisit(PatientDischargeDto input)
        //{

        //    var dbObj = await _uowPatientOpenVisit.Repository.GetById(input.PatientVisitId);

        //    if (AppCommonMethod.IsNullObject(dbObj))
        //        throw new UserFriendlyException(CommonMessageConstant.RecordNotFound);

        //    if (!AppCommonMethod.IsNullObject(dbObj) && dbObj!.IsDischarge == true)
        //        throw new UserFriendlyException(CommonMessageConstant.VisitClosed);

        //    FillEntityForDischargePatients(dbObj!);

        //    //if (!AppCommonMethod.IsNullObject(input.PatientDischargeDetails))
        //       var response = await _patientDischargeDetailService.CreatePatientDischargeUpdateVisit(input);

        //    _uowPatientOpenVisit.Repository.Update(dbObj!);
        //    await _uowPatientOpenVisit.CommitAsync();

        //    return input;
        //}

        public async Task<UpdateSscStatusAndDocumentDto> UpdateSscStatusAndDocumentDto(UpdateSscStatusAndDocumentDto input)
        {
            var dbObj = await _uowPatientOpenVisit.Repository.GetById(input.PatientVisitId);

            if (AppCommonMethod.IsNullObject(dbObj))
                throw new UserFriendlyException(CommonMessageConstant.RecordNotFound);

            if (!AppCommonMethod.IsNullorZeroInt(input.SscStatus) && dbObj.SscStatus != input.SscStatus)
            {
                dbObj.SscStatus = input.SscStatus;
                if (input.SscStatus == (int)SSCStatus.Claim_Rejected)
                    dbObj.SscStatusReason = input.SscStatusReason;
                else
                    dbObj.SscStatusReason = null;
                dbObj.SscStatusUpdatedOn = DateTime.Now;
                dbObj.SscStatusUpdatedBy = _tokenService.GetUserId();
            }

            //foreach (var document in input.PatientDocuments)
                await _patientDocumentService.UpdateAndInsert(input.PatientDocuments.ToList());

            _uowPatientOpenVisit.Repository.Update(dbObj!);
            await _uowPatientOpenVisit.CommitAsync();

            return input;
        }

        public async Task<CreateOrEditOpenVisitDto> UpdatePatientVisitForSscClaimed(PatientVisitSscClaimedDto input)
        {
            var dbObj = await _uowPatientOpenVisit.Repository.GetById(input.PatientOpenVisitId!);
            //var obj = _mapper.Map(input, dbObj);
            if (input.IsSscClaimed == true)
            {
                dbObj.IsSscClaimed = input.IsSscClaimed;
                dbObj.SscClaimedDate = DateTime.Now;

            }
            else
            {
                dbObj.ReasonIfSscNotClaimed = input.ReasonIfSscNotClaimed;
                dbObj.IsSscClaimed = input.IsSscClaimed ?? false;
            }

            FillEntity(dbObj);

            _uowPatientOpenVisit.Repository.Update(dbObj!);
            await _uowPatientOpenVisit.CommitAsync();

            return _mapper.Map<CreateOrEditOpenVisitDto>(dbObj);

        }

        public async Task<CreateorEditPatientEligibleForSSCDto> UpdatePatientEligibleForSSC(CreateorEditPatientEligibleForSSCDto input)
        {

            var dbObj = await _uowPatientOpenVisit.Repository.GetById(input.PatientOpenVisitId!);

            if (AppCommonMethod.IsNullObject(dbObj))
                throw new UserFriendlyException(CommonMessageConstant.RecordNotFound);

            var obj = _mapper.Map(input, dbObj);

            obj.SscNumber = input.SscNumber;
            obj.IsEligibleForSsc = input.IsEligibleForSsc;
            if(input.IsEligibleForSsc == true)
            {
                obj.SscStatus = (int)SSCStatus.Eligible;
                obj.SscStatusReason = null;
            }
            else
            {
                obj.SscStatus = (int)SSCStatus.Not_Eligible;
                obj.SscStatusReason = input.SscStatusReason;
            }

            _uowPatientOpenVisit.Repository.Update(obj!);
            await _uowPatientOpenVisit.CommitAsync();

            return _mapper.Map<CreateorEditPatientEligibleForSSCDto>(obj);
        }

        #endregion

        #region Read Operations

        public async Task<List<ViewPatientOpenVisitDto>> GetAll(Expression<Func<PatientOpenVisit, bool>>? filter = null,
            Func<IQueryable<TEntity>, IOrderedQueryable<TEntity>>? orderBy = null,
            string includeProperties = "")
        {
            List<PatientOpenVisit> responseObj = await _uowPatientOpenVisit.Repository.GetALL(filter).ToListAsync();
            return _mapper.Map<List<ViewPatientOpenVisitDto>>(responseObj);
        }

        public async Task<ViewPagerDto<ViewPatientVisitsListWithDetailDto>> GetPatientVisitsListWithDetail(FilterPatientVisitDto filter)
        {
            List<string> user = new List<string>();
            if (filter.User != null)
                user = filter!.User!.Split(',').ToList();

            
            var finalList = _uowPatientOpenVisit.GetDbContext().ViewPatientOpenVisiDashbaordLists
                .WhereIf(!string.IsNullOrEmpty(filter.FullName), x => x.PatientName!.ToLower().StartsWith(filter.FullName!))
                .WhereIf(!string.IsNullOrEmpty(filter.TokenNo), x => x.TokenNo == filter.TokenNo!.PadLeft(4, '0'))
                .WhereIf(!string.IsNullOrEmpty(filter.Cnic), x => x.Cnic == filter.Cnic)
                .WhereIf(!string.IsNullOrEmpty(filter.MobileNo), x => x.PatientMobileNo!.ToLower().StartsWith(filter.MobileNo!))
                .WhereIf(!string.IsNullOrEmpty(filter.Mrno), x => x.MrNo!.ToLower().StartsWith(filter.Mrno!))
                .WhereIf(!string.IsNullOrEmpty(filter.User), x => user.Contains(x.CreatedById.ToString()!))

                                //.WhereIf(!TokenService.IsSuperAdmin(), x => x.HealthFacilityId == TokenService.GetUserHfId())
                .WhereIf(!string.IsNullOrEmpty(filter.Relation) && filter.Relation != CommonConstants.Self, x => x.Relation != CommonConstants.Self)
                .WhereIf(!string.IsNullOrEmpty(filter.Relation) && filter.Relation == CommonConstants.Self, x => x.Relation == CommonConstants.Self)
                .WhereIf(AppCommonMethod.IsNullorZeroInt(filter.VisitNo), x => x.VisitNo > 0) //totalReg
                .WhereIf(!AppCommonMethod.IsNullorZeroInt(filter.VisitNo) && filter.VisitNo == 1, x => x.VisitNo == 1) //NewReg
                .WhereIf(!AppCommonMethod.IsNullorZeroInt(filter.VisitNo) && filter.VisitNo == 2, x => x.VisitNo > 1) //Revisit
                //.WhereIf(!AppCommonMethod.IsNullorZeroInt(filter.VisitNo) && filter.VisitNo == 1, x => x.PatientCreatedOn!.Value.Date >= filter.StartDate!.Value.Date)
                //.WhereIf(!AppCommonMethod.IsNullorZeroInt(filter.VisitNo) && filter.VisitNo == 1, x => x.PatientCreatedOn!.Value.Date < filter.EndDate!.Value.AddDays(1).Date)
                // .WhereIf(!AppCommonMethod.IsNullorZeroInt(filter.VisitNo) && filter.VisitNo == 1, x => x.CreatedOn!.Value.Date == x.PatientCreatedOn!.Value.Date)
                //.WhereIf(!AppCommonMethod.IsNullorZeroInt(filter.VisitNo) && filter.VisitNo == 1, x => x.VisitNo == filter.VisitNo)
                .WhereIf(!AppCommonMethod.IsNullorZeroInt(filter.MinAge), x => x.Age >= filter.MinAge)
                .WhereIf(!AppCommonMethod.IsNullorZeroInt(filter.MaxAge), x => x.Age <= filter.MaxAge)
                .WhereIf(!AppCommonMethod.IsNullOrEmptyGuid(filter.GenderId), x => x.GenderId == filter.GenderId)
                .WhereIf(!AppCommonMethod.IsNullorZeroInt(filter.PatientProvinceId), x => x.PatientProvinceId == filter.PatientProvinceId)
                .WhereIf(!AppCommonMethod.IsNullorZeroInt(filter.ProvinceId), x => x.ProvinceId == filter.ProvinceId)
                .WhereIf(!AppCommonMethod.IsNullorZeroInt(filter.DivisionId), x => x.DivisionId == filter.DivisionId)
                .WhereIf(!AppCommonMethod.IsNullorZeroInt(filter.DistrictId), x => x.DistrictId == filter.DistrictId)
                .WhereIf(!AppCommonMethod.IsNullorZeroInt(filter.TehsilId), x => x.TehsilId == filter.TehsilId)
                .WhereIf(!AppCommonMethod.IsNullorZeroInt(filter.DepartmentId), x => x.DepartementLookupId == filter.DepartmentId)
                .WhereIf(!AppCommonMethod.IsNullorZeroInt(filter.SectionId), x => x.SectionLookupId == filter.SectionId)
                .WhereIf(!AppCommonMethod.IsNullorZeroInt(filter.HealthFacilityId), x => x.HealthFacilityId == filter.HealthFacilityId)
                .WhereIf(!AppCommonMethod.IsNullorEmptyDate(filter.StartDate) , x => x.CreatedOn!.Value >= filter.StartDate!.Value)
                .WhereIf(!AppCommonMethod.IsNullorEmptyDate(filter.EndDate) , x => x.CreatedOn!.Value < filter.EndDate!.Value)




                .OrderByDescending(x => x.CreatedOn)
                .Select(x =>
                new ViewPatientVisitsListWithDetailDto
                {
                    PatientVisitId = x.PatientVisitId,
                    PatientId = x.PatientId,
                    FullName = x.PatientName,
                    MobileNo = x.PatientMobileNo,
                    PatientProvinceId = x.PatientProvinceId,
                    Mrno = x.MrNo,
                    Cnic = x.Cnic,
                    VisitDate = x.VisitDate,
                    CreatedBy = x.CreatedBy!,
                    CreatedOn = x.CreatedOn,
                    UpdatedBy = x.UpdatedBy!,
                    UpdatedOn = x.UpdatedOn,
                    DepartmentId = x.DepartementLookupId,
                    Department = x.Department,
                    Section = x.Section,
                    SectionId = x.SectionLookupId,
                    //PatientDiagnoseId = x.PatientDiagnoseId,
                    //FormType = x.FormType,
                    FirstName = x.FirstName,
                    LastName = x.LastName,
                    Gender = x.Gender,
                    Age = x.Age,
                    Dob = x.Dob,
                    IsDischarge = x.IsDischarge,
                    IsVitalSkip = x.IsVitalSkip,
                    IsSscClaimed = x.IsSscClaimed,
                    SscNotConfirmReason = x.SscNotConfirmReason,
                    SscStatus = x.SscStatus,
                    SscStatusName = x.SscStatusName,
                    SscClaimedDate = x.SscClaimedDate,
                    SscStatusReason = x.SscStatusReason,
                    SscStatusUpdatedOn = x.SscStatusUpdatedOn,
                    SscStatusUpdatedBy = x.SscStatusUpdatedBy,
                    SscNumber = x.SscNumber,
                    IsEligibleForSsc = x.IsEligibleForSsc,
                    SscNotEligibleReason = x.SscNotEligibleReason,
                    HealthFacilityName = x.HealthFacilityName,  
                    HealthFacilityId = x.HealthFacilityId,
                    TokenNo = x.TokenNo,
                    IsReferred = x.IsReferred,
                    ReferredByDepartmentLookupId = x.ReferredByDepartmentLookupId,
                    ReferredBySectionLookupId = x.ReferredBySectionLookupId

                });

            var pagedList = await PagedListDto<ViewPatientVisitsListWithDetailDto>.ToPagedListAsync(
                   finalList,
                   filter.PageNumber,
                   filter.PageSize
                   );

            var responseObject = new ViewPagerDto<ViewPatientVisitsListWithDetailDto>
            {
                TotalCount = pagedList.TotalCount,
                PageSize = pagedList.PageSize,
                CurrentPage = pagedList.CurrentPage,
                TotalPages = pagedList.TotalPages,
                HasNext = pagedList.HasNext,
                HasPrevious = pagedList.HasPrevious,
                List = pagedList
            };

            return responseObject;
        }

        public async Task<ViewPagerDto<ViewPatientVisitsListWithDetailDto>> GetIPDPatientVisitsListWithDetail(FilterPatientVisitDto filter)
        {
            List<string> user = new List<string>();
            if (filter.User != null)
                user = filter!.User!.Split(',').ToList();

            var finalList = _uowPatientOpenVisit.GetDbContext().ViewPatientOpenVisitLists
                .WhereIf(!string.IsNullOrEmpty(filter.FullName), x => x.PatientName!.ToLower().StartsWith(filter.FullName!))
                .WhereIf(!string.IsNullOrEmpty(filter.TokenNo), x => x.TokenNo == filter.TokenNo!.PadLeft(4, '0'))
                .WhereIf(!string.IsNullOrEmpty(filter.Cnic), x => x.Cnic == filter.Cnic)
                .WhereIf(!string.IsNullOrEmpty(filter.MobileNo), x => x.PatientMobileNo!.ToLower().StartsWith(filter.MobileNo!))
                .WhereIf(!string.IsNullOrEmpty(filter.Mrno), x => x.MrNo!.ToLower().StartsWith(filter.Mrno!))
                .WhereIf(!string.IsNullOrEmpty(filter.User), x => user.Contains(x.CreatedById.ToString()!))

                //.WhereIf(!TokenService.IsSuperAdmin(), x => x.HealthFacilityId == TokenService.GetUserHfId())
                .WhereIf(!string.IsNullOrEmpty(filter.Relation) && filter.Relation != CommonConstants.Self, x => x.Relation != CommonConstants.Self)
                .WhereIf(!string.IsNullOrEmpty(filter.Relation) && filter.Relation == CommonConstants.Self, x => x.Relation == CommonConstants.Self)
                .WhereIf(AppCommonMethod.IsNullorZeroInt(filter.VisitNo), x => x.VisitNo > 0) //totalReg
                .WhereIf(!AppCommonMethod.IsNullorZeroInt(filter.VisitNo) && filter.VisitNo == 1, x => x.VisitNo == 1) //NewReg
                .WhereIf(!AppCommonMethod.IsNullorZeroInt(filter.VisitNo) && filter.VisitNo == 2, x => x.VisitNo > 1) //Revisit
                .WhereIf(!AppCommonMethod.IsNullorZeroInt(filter.MinAge), x => x.Age >= filter.MinAge)
                .WhereIf(!AppCommonMethod.IsNullorZeroInt(filter.MaxAge), x => x.Age <= filter.MaxAge)
                .WhereIf(!AppCommonMethod.IsNullOrEmptyGuid(filter.GenderId), x => x.GenderId == filter.GenderId)
                .WhereIf(!AppCommonMethod.IsNullorZeroInt(filter.PatientProvinceId), x => x.PatientProvinceId == filter.PatientProvinceId)
                .WhereIf(!AppCommonMethod.IsNullorZeroInt(filter.ProvinceId), x => x.ProvinceId == filter.ProvinceId)
                .WhereIf(!AppCommonMethod.IsNullorZeroInt(filter.DivisionId), x => x.DivisionId == filter.DivisionId)
                .WhereIf(!AppCommonMethod.IsNullorZeroInt(filter.DistrictId), x => x.DistrictId == filter.DistrictId)
                .WhereIf(!AppCommonMethod.IsNullorZeroInt(filter.TehsilId), x => x.TehsilId == filter.TehsilId)
                .WhereIf(!AppCommonMethod.IsNullorZeroInt(filter.HealthFacilityId), x => x.HealthFacilityId == filter.HealthFacilityId)
                .WhereIf(!AppCommonMethod.IsNullorZeroInt(filter.DepartmentId), x => x.DepartementLookupId == filter.DepartmentId)
                .WhereIf(!AppCommonMethod.IsNullorZeroInt(filter.SectionId), x => x.SectionLookupId == filter.SectionId)
                //.WhereIf(AppCommonMethod.IsNull(filter.SscStatus), x => x.SscStatus == (int)SSCStatus.Pending || x.SscStatus == null)
                //.WhereIf(!AppCommonMethod.IsNullorZeroInt(filter.SscStatus) && filter.SscStatus != (int)SSCStatus.Pending, x => x.SscStatus == filter.SscStatus)
                .WhereIf(!AppCommonMethod.IsNullorZeroInt(filter.SscStatus), x => x.SscStatus == filter.SscStatus)
                .WhereIf(!AppCommonMethod.IsNullorEmptyDate(filter.StartDate), x => x.CreatedOn!.Value.Date >= filter.StartDate!.Value.Date)
                .WhereIf(!AppCommonMethod.IsNullorEmptyDate(filter.EndDate), x => x.CreatedOn!.Value.Date < filter.EndDate!.Value.AddDays(1).Date)

                .OrderByDescending(x => x.CreatedOn)
                .Select(x =>
                new ViewPatientVisitsListWithDetailDto
                {
                    PatientVisitId = x.PatientVisitId,
                    PatientId = x.PatientId,
                    FullName = x.PatientName,
                    MobileNo = x.PatientMobileNo,
                    PatientProvinceId = x.PatientProvinceId,
                    Mrno = x.MrNo,
                    Cnic = x.Cnic,
                    VisitDate = x.VisitDate,
                    CreatedBy = x.CreatedBy!,
                    CreatedOn = x.CreatedOn,
                    UpdatedBy = x.UpdatedBy!,
                    UpdatedOn = x.UpdatedOn,
                    DepartmentId = x.DepartementLookupId,
                    Department = x.Department,
                    Section = x.Section,
                    SectionId = x.SectionLookupId,
                    //PatientDiagnoseId = x.PatientDiagnoseId,
                    //FormType = x.FormType,
                    FirstName = x.FirstName,
                    LastName = x.LastName,
                    Gender = x.Gender,
                    Age = x.Age,

                    SscStatus = x.SscStatus,
                    SscStatusReason = x.SscStatusReason,
                    SscStatusName = x.SscStatusName,
                    SscStatusUpdatedOn = x.SscStatusUpdatedOn,
                    SscStatusUpdatedBy = x.SscStatusUpdatedBy,

                    IsDischarge = x.IsDischarge,
                    IsVitalSkip = x.IsVitalSkip,
                    IsSscClaimed = x.IsSscClaimed,
                    SscNotConfirmReason = x.SscNotConfirmReason,
                    SscNumber = x.SscNumber,
                    IsEligibleForSsc = x.IsEligibleForSsc,
                    SscNotEligibleReason = x.SscNotEligibleReason,
                    HealthFacilityName = x.HealthFacilityName,
                    HealthFacilityId = x.HealthFacilityId,
                    TokenNo = x.TokenNo,
                });

            var pagedList = await PagedListDto<ViewPatientVisitsListWithDetailDto>.ToPagedListAsync(
                   finalList,
                   filter.PageNumber,
                   filter.PageSize
                   );

            var responseObject = new ViewPagerDto<ViewPatientVisitsListWithDetailDto>
            {
                TotalCount = pagedList.TotalCount,
                PageSize = pagedList.PageSize,
                CurrentPage = pagedList.CurrentPage,
                TotalPages = pagedList.TotalPages,
                HasNext = pagedList.HasNext,
                HasPrevious = pagedList.HasPrevious,
                List = pagedList
            };

            return responseObject;
        }

        //public async Task<ViewPagerDto<ViewPatientVisitsListWithDetailDto>> GetPatientVisitsListWithDetail(FilterPatientVisitDto filter)
        //{
        //    List<string> user = new List<string>();
        //    if (filter.User != null)
        //        user = filter!.User!.Split(',').ToList();


        //    var finalList = _uowPatientOpenVisit.GetDbContext().ViewPatientOpenVisitLists
        //        .WhereIf(!string.IsNullOrEmpty(filter.FullName), x => x.PatientName!.ToLower().StartsWith(filter.FullName!))
        //        .WhereIf(!string.IsNullOrEmpty(filter.Cnic), x => x.Cnic == filter.Cnic)
        //        .WhereIf(!string.IsNullOrEmpty(filter.MobileNo), x => x.PatientMobileNo!.ToLower().StartsWith(filter.MobileNo!))
        //        .WhereIf(!string.IsNullOrEmpty(filter.Mrno), x => x.MrNo!.ToLower().StartsWith(filter.Mrno!))
        //        .WhereIf(!string.IsNullOrEmpty(filter.User), x => user.Contains(x.CreatedById.ToString()!))

        //                        //.WhereIf(!TokenService.IsSuperAdmin(), x => x.HealthFacilityId == TokenService.GetUserHfId())
        //        .WhereIf(!string.IsNullOrEmpty(filter.Relation) && filter.Relation != CommonConstants.Self, x => x.Relation != CommonConstants.Self)
        //        .WhereIf(!string.IsNullOrEmpty(filter.Relation) && filter.Relation == CommonConstants.Self, x => x.Relation == CommonConstants.Self)
        //        .WhereIf(!AppCommonMethod.IsNullorZeroInt(filter.VisitNo) && filter.VisitNo > 1, x => x.VisitNo > 1)
        //         //.WhereIf(!AppCommonMethod.IsNullorZeroInt(filter.VisitNo) && filter.VisitNo == 1, x => x.PatientCreatedOn!.Value.Date >= filter.StartDate!.Value.Date)
        //         //.WhereIf(!AppCommonMethod.IsNullorZeroInt(filter.VisitNo) && filter.VisitNo == 1, x => x.PatientCreatedOn!.Value.Date < filter.EndDate!.Value.AddDays(1).Date)
        //         // .WhereIf(!AppCommonMethod.IsNullorZeroInt(filter.VisitNo) && filter.VisitNo == 1, x => x.CreatedOn!.Value.Date == x.PatientCreatedOn!.Value.Date)
        //        .WhereIf(!AppCommonMethod.IsNullorZeroInt(filter.VisitNo) && filter.VisitNo == 1, x => x.VisitNo == filter.VisitNo)
        //        .WhereIf(!AppCommonMethod.IsNullorZeroInt(filter.MinAge), x => x.Age >= filter.MinAge)
        //        .WhereIf(!AppCommonMethod.IsNullorZeroInt(filter.MaxAge), x => x.Age <= filter.MaxAge)
        //        .WhereIf(!AppCommonMethod.IsNullOrEmptyGuid(filter.GenderId), x => x.GenderId == filter.GenderId)
        //        .WhereIf(!AppCommonMethod.IsNullorZeroInt(filter.PatientProvinceId), x => x.PatientProvinceId == filter.PatientProvinceId)
        //        .WhereIf(!AppCommonMethod.IsNullorZeroInt(filter.ProvinceId), x => x.ProvinceId == filter.ProvinceId)
        //        .WhereIf(!AppCommonMethod.IsNullorZeroInt(filter.DivisionId), x => x.DivisionId == filter.DivisionId)
        //        .WhereIf(!AppCommonMethod.IsNullorZeroInt(filter.DistrictId), x => x.DistrictId == filter.DistrictId)
        //        .WhereIf(!AppCommonMethod.IsNullorZeroInt(filter.TehsilId), x => x.TehsilId == filter.TehsilId)
        //        .WhereIf(!AppCommonMethod.IsNullorZeroInt(filter.DepartmentId), x => x.DepartementLookupId == filter.DepartmentId)
        //        .WhereIf(!AppCommonMethod.IsNullorZeroInt(filter.SectionId), x => x.SectionLookupId == filter.SectionId)
        //        .WhereIf(!AppCommonMethod.IsNullorZeroInt(filter.HealthFacilityId), x => x.HealthFacilityId == filter.HealthFacilityId)
        //        .WhereIf(!AppCommonMethod.IsNullorEmptyDate(filter.StartDate) , x => x.CreatedOn!.Value.Date >= filter.StartDate!.Value.Date)
        //        .WhereIf(!AppCommonMethod.IsNullorEmptyDate(filter.EndDate) , x => x.CreatedOn!.Value.Date < filter.EndDate!.Value.AddDays(1).Date)



        //        .OrderByDescending(x => x.CreatedOn)
        //        .Select(x =>
        //        new ViewPatientVisitsListWithDetailDto
        //        {
        //            PatientVisitId = x.PatientVisitId,
        //            PatientId = x.PatientId,
        //            FullName = x.PatientName,
        //            MobileNo = x.PatientMobileNo,
        //            PatientProvinceId = x.PatientProvinceId,
        //            Mrno = x.MrNo,
        //            Cnic = x.Cnic,
        //            VisitDate = x.VisitDate,
        //            CreatedBy = x.CreatedBy!,
        //            CreatedOn = x.CreatedOn,
        //            UpdatedBy = x.UpdatedBy!,
        //            UpdatedOn = x.UpdatedOn,
        //            Department = x.Department,
        //            Section = x.Section,
        //            PatientDiagnoseId = x.PatientDiagnoseId,
        //            FormType = x.FormType,
        //            FirstName = x.FirstName,
        //            LastName = x.LastName,
        //            Gender = x.Gender,
        //            Age = x.Age,
        //            IsDischarge = x.IsDischarge,
        //            IsVitalSkip = x.IsVitalSkip
        //        });

        //    var pagedList = await PagedListDto<ViewPatientVisitsListWithDetailDto>.ToPagedListAsync(
        //           finalList,
        //           filter.PageNumber,
        //           filter.PageSize
        //           );

        //    var responseObject = new ViewPagerDto<ViewPatientVisitsListWithDetailDto>
        //    {
        //        TotalCount = pagedList.TotalCount,
        //        PageSize = pagedList.PageSize,
        //        CurrentPage = pagedList.CurrentPage,
        //        TotalPages = pagedList.TotalPages,
        //        HasNext = pagedList.HasNext,
        //        HasPrevious = pagedList.HasPrevious,
        //        List = pagedList
        //    };

        //    return responseObject;
        //}

        public async Task<ViewPatientOpenVisitDto> GetById(Guid input)
        {
            PatientOpenVisit? responseObj = await _uowPatientOpenVisit.Repository.GetById(input);

            if (AppCommonMethod.IsNullObject(responseObj))
                throw new UserFriendlyException(CommonMessageConstant.RecordNotFound);

            return _mapper.Map<ViewPatientOpenVisitDto>(responseObj);
        }


        public async Task<ViewPagerDto<ViewPatientVisitsListWithDetailDto>> GetTodayVisits(FilterPatientVisitDto filter)
        {
            var diagnosedBy = _tokenService.GetUserId();

            var list = _uowPatientDiagnose.Repository.GetALL(x => 
                x.ActionTypeId != (int)ActionTypeEnum.Deleted
                && x.DiagnosedBy == diagnosedBy
                && x.PatientVisit!.VisitDate == DateTime.Today 
                && x.PatientVisit.HealthFacilityId == TokenService.GetUserHfId());



            list = list
                .WhereIf(!string.IsNullOrEmpty(filter.Cnic), x => x.Patient!.Cnic.Replace("-", String.Empty) == filter.Cnic)
                .WhereIf(!string.IsNullOrEmpty(filter.FullName), x => x.Patient!.FullName!.StartsWith(filter.FullName!))
                .WhereIf(!string.IsNullOrEmpty(filter.MobileNo), x => x.Patient!.MobileNo!.StartsWith(filter.MobileNo!))
                .WhereIf(!string.IsNullOrEmpty(filter.Mrno), x => x.Patient!.Mrno!.StartsWith(filter.Mrno!))
                .OrderByDescending(x => x.CreatedOn);

            IQueryable<ViewPatientVisitsListWithDetailDto> IQueryableList = list.Select(y =>
                new ViewPatientVisitsListWithDetailDto
                {
                    PatientId = y.PatientId,
                    PatientVisitId = y.PatientVisitId,
                    Mrno = y.Patient!.Mrno,
                    Cnic = y.Patient.Cnic,
                    FirstName = y.Patient.FirstName,
                    LastName = y.Patient.LastName,
                    FullName = y.Patient.FullName,
                    TokenNo = y.PatientVisit!.TokenNo,
                    VisitNo = y.PatientVisit!.VisitNo,
                    VisitDate = y.PatientVisit.VisitDate,
                    IsDischarge = y.PatientVisit.IsDischarge,
                    MobileNo = y.Patient.MobileNo
                });



            var pagedList = await PagedListDto<ViewPatientVisitsListWithDetailDto>.ToPagedListAsync(
                   IQueryableList,
                   filter.PageNumber,
                   filter.PageSize
                   );

            var responseObject = new ViewPagerDto<ViewPatientVisitsListWithDetailDto>
            {
                TotalCount = pagedList.TotalCount,
                PageSize = pagedList.PageSize,
                CurrentPage = pagedList.CurrentPage,
                TotalPages = pagedList.TotalPages,
                HasNext = pagedList.HasNext,
                HasPrevious = pagedList.HasPrevious,
                List = pagedList
            };

            return responseObject;
        }

        public async Task<ViewPagerDto<ViewPatientVisitsListWithDetailDto>> GetOldVisits(FilterPatientVisitDto filter)
        {
            var diagnosedBy = _tokenService.GetUserId();

            //var responseObj = await _uowPatientDiagnose.Repository.GetALL(x => x.DiagnosedBy == diagnosedBy && x.PatientVisit!.VisitDate < DateTime.Today).Select(y => new ViewPatientVisitsListWithDetailDto
            //{
            //    PatientId = y.PatientId,
            //    PatientVisitId = y.PatientVisitId,
            //    Mrno = y.Patient!.Mrno,
            //    Cnic = y.Patient.Cnic,
            //    FirstName = y.Patient.FirstName,
            //    LastName = y.Patient.LastName,
            //    FullName = y.Patient.FullName,
            //    TokenNo = y.PatientVisit!.TokenNo,
            //    VisitNo = y.PatientVisit!.VisitNo,
            //    VisitDate = y.PatientVisit.VisitDate,
            //    IsDischarge = y.PatientVisit.IsDischarge,
            //    MobileNo = y.Patient.MobileNo
            //}).ToListAsync();

            //if (AppCommonMethod.IsNullObject(responseObj))
            //    throw new UserFriendlyException(CommonMessageConstant.RecordNotFound);

            //return _mapper.Map<List<ViewPatientVisitsListWithDetailDto>>(responseObj);
            //return null;

            // get visits of health facility of login person
            var list = _uowPatientDiagnose.Repository.GetALL(x =>
            x.ActionTypeId != (int)ActionTypeEnum.Deleted
            && x.DiagnosedBy == diagnosedBy
            && x.PatientVisit!.VisitDate < DateTime.Today && x.PatientVisit.HealthFacilityId == TokenService.GetUserHfId());
            

            list = list
                .WhereIf(!string.IsNullOrEmpty(filter.Cnic), x => x.Patient!.Cnic.Replace("-", String.Empty) == filter.Cnic)
                .WhereIf(!string.IsNullOrEmpty(filter.FullName), x => x.Patient!.FullName!.StartsWith(filter.FullName!))
                .WhereIf(!string.IsNullOrEmpty(filter.MobileNo), x => x.Patient!.MobileNo!.StartsWith(filter.MobileNo!))
                .WhereIf(!string.IsNullOrEmpty(filter.Mrno), x => x.Patient!.Mrno!.StartsWith(filter.Mrno!))
                .OrderByDescending(x=>x.CreatedOn);

            IQueryable<ViewPatientVisitsListWithDetailDto> IQueryableList = list.Select(y =>
                new ViewPatientVisitsListWithDetailDto
                {
                    PatientId = y.PatientId,
                    PatientVisitId = y.PatientVisitId,
                    Mrno = y.Patient!.Mrno,
                    Cnic = y.Patient.Cnic,
                    FirstName = y.Patient.FirstName,
                    LastName = y.Patient.LastName,
                    FullName = y.Patient.FullName,
                    TokenNo = y.PatientVisit!.TokenNo,
                    VisitNo = y.PatientVisit!.VisitNo,
                    VisitDate = y.PatientVisit.VisitDate,
                    IsDischarge = y.PatientVisit.IsDischarge,
                    MobileNo = y.Patient.MobileNo

                });



            var pagedList = await PagedListDto<ViewPatientVisitsListWithDetailDto>.ToPagedListAsync(
                   IQueryableList,
                   filter.PageNumber,
                   filter.PageSize
                   );

            var responseObject = new ViewPagerDto<ViewPatientVisitsListWithDetailDto>
            {
                TotalCount = pagedList.TotalCount,
                PageSize = pagedList.PageSize,
                CurrentPage = pagedList.CurrentPage,
                TotalPages = pagedList.TotalPages,
                HasNext = pagedList.HasNext,
                HasPrevious = pagedList.HasPrevious,
                List = pagedList
            };

            return responseObject;
        }

        public async Task<List<ViewPatientGlobalQueDto>> GetAllQue(string searchValue)
        {
            var _uowUser = new UnitOfWork<User>(_uowPatientDiagnose.GetDbContext());
            //var dbUser = await _uowUser.Repository.GetALL(x => x.UserId == _tokenService.GetUserId()).FirstOrDefaultAsync();
            var user = TokenService.GetUserLoggedInfo();

            //Doctor Station 
            //var _uowProfile = new UnitOfWork<DbModel.Profile>(_uowPatientDiagnose.GetDbContext());
            //Guid? doctorStation = await _uowProfile.Repository.GetALL(x => x.ShortName == CommonStringConstant.DoctorStation).Select(x => x.ProfileId).FirstOrDefaultAsync();
                

            var responseObj = await _uowPatientOpenVisit.Repository.GetALL(x => 
                    x.HealthFacilityId == user!.HealthFacilityId)

                // Only show user department Patients
                .WhereIf(!AppCommonMethod.IsNullorZeroInt(user!.DepartmentId), x => x.DepartementLookupId == user.DepartmentId)

                // If IPD / ER don't show Discharge Patients
                .WhereIf((user.DepartmentName != CommonStringConstant.OutPatientDepartment), x => x.IsDischarge != true)

                // If IPD don't show until Patient is Admitted in IPD
                .WhereIf((user.DepartmentName == CommonStringConstant.InPatientDepartment), x => x.VisitFor == CommonStringConstant.IPD && x.IsAdmitted == true)
                .WhereIf((user.DepartmentName == CommonStringConstant.ERDepartment), x => x.VisitFor == CommonStringConstant.ER && x.IsAdmitted == true)

                // if  OPD or NULL then only show today patient and OPD patient
                .WhereIf((AppCommonMethod.IsNullorZeroInt(user!.DepartmentId) || user.DepartmentName == CommonStringConstant.OutPatientDepartment), x => x.VisitDate == DateTime.Today && (x.VisitFor == CommonStringConstant.OPD || x.VisitFor == null))

                .WhereIf(!string.IsNullOrEmpty(searchValue), x => 
                    x.TokenNo == searchValue.PadLeft(4, '0') 
                    || x.Patient!.Mrno == searchValue 
                    || x.Patient!.Cnic == AppCommonMethod.AddDashesInCnic(searchValue) || x.Patient!.Cnic == AppCommonMethod.RemoveDashes(searchValue)
                    )
                .Include(x => x.Patient)
                .Include(x => x.PatientDiagnoses)
                .OrderBy(x => x.TokenNo)
                .Select(y =>
                    new ViewPatientGlobalQueDto
                    {
                        PatientVisitId = y.PatientOpenVisitId,
                        PatientId = y.PatientId,
                        TokenNo = y.TokenNo,
                        Mrno = y.Patient!.Mrno,
                        CNIC = y.Patient.Cnic,
                        MobileNo = y.Patient.MobileNo,
                        FirstName = y.Patient.FirstName,
                        LastName = y.Patient.LastName,
                        FullName = y.Patient.FullName,
                        Relation = y.Patient.RelationProfile!.Name,
                        SelfOccupied = y.OccupiedBy == _tokenService.GetUserId() ? true : false,
                        IsOccupied = y.IsOccupied,
                        OccupiedBy = y.OccupiedBy,
                        OccupiedByName = y.OccupiedByNavigation!.FullName,
                        IsVisitClose = y.IsDischarge,
                        DepartmentName = y.DepartementLookup!.Name,
                        SectionName = y.SectionLookup!.Name,
                        IsPickFromGlobalQueue = true,
                        IsAlreadyAttended = (y.PatientDiagnoses.IsNullOrEmpty()) ? false : true,
                        IsSelfAttended = (y.PatientDiagnoses.Where(x => x.DiagnosedBy == _tokenService.GetUserId()).IsNullOrEmpty()) ? false : true,
                        AttendedDiagnoseLists = y.PatientDiagnoses.Select(x => new ViewAttendedDiagnoseListForGlobalQueDto
                        {
                            PatientDiagnoseId = x.PatientDiagnoseId,
                            PatientVisitId = x.PatientVisitId,
                            DiagnosedBy = x.DiagnosedBy,
                            DiagnosedByName = x.DiagnosedByNavigation!.FullName,
                            DiagnosedByDesignation = x.DiagnosedByNavigation!.DesignationProfile!.Name,
                            Speciality = x.DocSectionLookup!.Name,
                            FormType = x.DocSectionLookup!.FormType,
                            CreatedOn = x.CreatedOn,
                        }).ToList()
                    }).ToListAsync();

            return _mapper.Map<List<ViewPatientGlobalQueDto>>(responseObj);
        }


        public async Task<PatientDetailsForReferralSlipByVisitIdDTO> GetPatientDetailsForReferralSlipByVisitId(Guid VisitId)
        {
            using (var db = new HmisAuthContext())
            {
                var conn = _uowPatientOpenVisit.GetDbContext().Database.GetDbConnection();
                try
                {
                    DataSet ds = new DataSet();
                    SqlCommand sqlComm = new SqlCommand("[dbo].[SPGetPatientDetailsForReferralSlipByVisitId]", (SqlConnection)conn);
                    sqlComm.CommandType = CommandType.StoredProcedure;

                    if (!AppCommonMethod.IsNullOrEmptyGuid(VisitId))
                        sqlComm.Parameters.AddWithValue("@PatientOpenVisitId", VisitId);

                    SqlDataAdapter da = new SqlDataAdapter();
                    da.SelectCommand = sqlComm;
                    await Task.Run(() => da.Fill(ds));
                    List<PatientDetailsForReferralSlipByVisitIdDTO> lst = ds.Tables[0].ToList<PatientDetailsForReferralSlipByVisitIdDTO>();
                    List<PatientVitalsDetailsForReferralSlipByVisitIdDTO> vitalLst = ds.Tables[1].ToList<PatientVitalsDetailsForReferralSlipByVisitIdDTO>();
                    var patientDetails = lst.FirstOrDefault();
                    if (patientDetails != null)
                    {
                        patientDetails.Vitals = vitalLst;
                    }

                    return patientDetails;
                }
                catch (Exception)
                {
                    throw;
                }
                finally
                {
                    conn.Close();
                }
            }
        }


        // All Patient Visit list which are discharged
        public async Task<ViewPagerDto<ViewPatientVisitsListWithDetailDto>> GetDischargedPatientVisitsListWithDetail(FilterPatientVisitDto filter)
        {
            List<string> user = new List<string>();
            if (filter.User != null)
                user = filter!.User!.Split(',').ToList();


            var finalList = _uowPatientOpenVisit.GetDbContext().ViewPatientDischargeLists.Where(x => x.IsDischarge == true)
                //.WhereIf(!string.IsNullOrEmpty(filter.FullName), x => x.PatientName!.ToLower().StartsWith(filter.FullName!))
                //.WhereIf(!string.IsNullOrEmpty(filter.TokenNo), x => x.TokenNo == filter.TokenNo!.PadLeft(4, '0'))
                .WhereIf(!string.IsNullOrEmpty(filter.Cnic), x => x.Cnic == filter.Cnic)
                .WhereIf(!string.IsNullOrEmpty(filter.MobileNo), x => x.PatientMobileNo!.ToLower().StartsWith(filter.MobileNo!))
                .WhereIf(!string.IsNullOrEmpty(filter.Mrno), x => x.MrNo!.ToLower().StartsWith(filter.Mrno!))
                //.WhereIf(!string.IsNullOrEmpty(filter.User), x => user.Contains(x.CreatedById.ToString()!))
                //.WhereIf(!AppCommonMethod.IsNullorZeroInt(filter.ProvinceId), x => x.ProvinceId == filter.ProvinceId)
                .WhereIf(!AppCommonMethod.IsNullorZeroInt(filter.DivisionId), x => x.DivisionId == filter.DivisionId)
                .WhereIf(!AppCommonMethod.IsNullorZeroInt(filter.DistrictId), x => x.DistrictId == filter.DistrictId)
                .WhereIf(!AppCommonMethod.IsNullorZeroInt(filter.TehsilId), x => x.TehsilId == filter.TehsilId)
                .WhereIf(!AppCommonMethod.IsNullorZeroInt(filter.DepartmentId), x => x.DepartementLookupId == filter.DepartmentId)
                //.WhereIf(!AppCommonMethod.IsNullorZeroInt(filter.SectionId), x => x.SectionLookupId == filter.SectionId)
                .WhereIf(!AppCommonMethod.IsNullorZeroInt(filter.HealthFacilityId), x => x.HealthFacilityId == filter.HealthFacilityId)
                .WhereIf(!AppCommonMethod.IsNullorEmptyDate(filter.StartDate), x => x.CreatedOn!.Value.Date >= filter.StartDate!.Value.Date)
                .WhereIf(!AppCommonMethod.IsNullorEmptyDate(filter.EndDate), x => x.CreatedOn!.Value.Date < filter.EndDate!.Value.AddDays(1).Date)



                .OrderByDescending(x => x.CreatedOn)
                .Select(x =>
                new ViewPatientVisitsListWithDetailDto
                {
                    PatientVisitId = x.PatientVisitId,
                    PatientId = x.PatientId,
                    FullName = x.PatientName,
                    MobileNo = x.PatientMobileNo,
                    PatientProvinceId = x.PatientProvinceId,
                    Mrno = x.MrNo,
                    Cnic = x.Cnic,
                    VisitDate = x.VisitDate,
                    CreatedBy = x.CreatedBy!,
                    CreatedOn = x.CreatedOn,
                    UpdatedBy = x.UpdatedBy!,
                    UpdatedOn = x.UpdatedOn,
                    Department = x.Department,
                    Section = x.Section,
                    PatientDiagnoseId = x.PatientDiagnoseId,
                    FormType = x.FormType,
                    IsDischarge = x.IsDischarge,
                    IsRefer = x.IsRefer,
                    IsSscClaimed = x.IsSscClaimed,
                    SscNotConfirmReason = x.SscNotConfirmReason,
                    SscClaimedDate = x.SscClaimedDate,
                    
                    IsEligibleForSsc = x.IsEligibleForSsc,
                    SscNumber = x.SscNumber,
                    SscNotEligibleReason = x.SscNotEligibleReason
                });

            var pagedList = await PagedListDto<ViewPatientVisitsListWithDetailDto>.ToPagedListAsync(
                   finalList,
                   filter.PageNumber,
                   filter.PageSize
                   );

            var responseObject = new ViewPagerDto<ViewPatientVisitsListWithDetailDto>
            {
                TotalCount = pagedList.TotalCount,
                PageSize = pagedList.PageSize,
                CurrentPage = pagedList.CurrentPage,
                TotalPages = pagedList.TotalPages,
                HasNext = pagedList.HasNext,
                HasPrevious = pagedList.HasPrevious,
                List = pagedList
            };

            return responseObject;
        }

        // All Patient Visit list which are discharged and eligibel for SSC but SSC is not claimed and Claim is not confirm
        public async Task<ViewPagerDto<ViewPatientVisitsListWithDetailDto>> GetDischargedButNotSscClaimedPatientVisitsListWithDetail(FilterPatientVisitDto filter)
        {
            List<string> user = new List<string>();
            if (filter.User != null)
                user = filter!.User!.Split(',').ToList();


            var finalList = _uowPatientOpenVisit.GetDbContext().ViewPatientOpenVisitLists.Where(x => x.IsDischarge == true && x.IsEligibleForSsc == true && x.IsSscClaimed == null && x.ReasonIfSscNotClaimed == null)
                .WhereIf(!string.IsNullOrEmpty(filter.FullName), x => x.PatientName!.ToLower().StartsWith(filter.FullName!))
                .WhereIf(!string.IsNullOrEmpty(filter.TokenNo), x => x.TokenNo == filter.TokenNo!.PadLeft(4, '0'))
                .WhereIf(!string.IsNullOrEmpty(filter.Cnic), x => x.Cnic == filter.Cnic)
                .WhereIf(!string.IsNullOrEmpty(filter.MobileNo), x => x.PatientMobileNo!.ToLower().StartsWith(filter.MobileNo!))
                .WhereIf(!string.IsNullOrEmpty(filter.Mrno), x => x.MrNo!.ToLower().StartsWith(filter.Mrno!))
                .WhereIf(!string.IsNullOrEmpty(filter.User), x => user.Contains(x.CreatedById.ToString()!))
                .WhereIf(!AppCommonMethod.IsNullorZeroInt(filter.ProvinceId), x => x.ProvinceId == filter.ProvinceId)
                .WhereIf(!AppCommonMethod.IsNullorZeroInt(filter.DivisionId), x => x.DivisionId == filter.DivisionId)
                .WhereIf(!AppCommonMethod.IsNullorZeroInt(filter.DistrictId), x => x.DistrictId == filter.DistrictId)
                .WhereIf(!AppCommonMethod.IsNullorZeroInt(filter.TehsilId), x => x.TehsilId == filter.TehsilId)
                .WhereIf(!AppCommonMethod.IsNullorZeroInt(filter.DepartmentId), x => x.DepartementLookupId == filter.DepartmentId)
                .WhereIf(!AppCommonMethod.IsNullorZeroInt(filter.SectionId), x => x.SectionLookupId == filter.SectionId)
                .WhereIf(!AppCommonMethod.IsNullorZeroInt(filter.HealthFacilityId), x => x.HealthFacilityId == filter.HealthFacilityId)
                .WhereIf(!AppCommonMethod.IsNullorEmptyDate(filter.StartDate), x => x.CreatedOn!.Value.Date >= filter.StartDate!.Value.Date)
                .WhereIf(!AppCommonMethod.IsNullorEmptyDate(filter.EndDate), x => x.CreatedOn!.Value.Date < filter.EndDate!.Value.AddDays(1).Date)



                .OrderByDescending(x => x.CreatedOn)
                .Select(x =>
                new ViewPatientVisitsListWithDetailDto
                {
                    PatientVisitId = x.PatientVisitId,
                    PatientId = x.PatientId,
                    FullName = x.PatientName,
                    MobileNo = x.PatientMobileNo,
                    PatientProvinceId = x.PatientProvinceId,
                    Mrno = x.MrNo,
                    Cnic = x.Cnic,
                    VisitDate = x.VisitDate,
                    CreatedBy = x.CreatedBy!,
                    CreatedOn = x.CreatedOn,
                    UpdatedBy = x.UpdatedBy!,
                    UpdatedOn = x.UpdatedOn,
                    Department = x.Department,
                    Section = x.Section,
                    PatientDiagnoseId = x.PatientDiagnoseId,
                    FormType = x.FormType,
                    IsDischarge = x.IsDischarge,

                    IsSscClaimed = x.IsSscClaimed,
                    SscNotConfirmReason = x.SscNotConfirmReason,
                    SscClaimedDate = x.SscClaimedDate,

                    IsEligibleForSsc = x.IsEligibleForSsc,
                    SscNumber = x.SscNumber,
                    SscNotEligibleReason = x.SscNotEligibleReason
                });

            var pagedList = await PagedListDto<ViewPatientVisitsListWithDetailDto>.ToPagedListAsync(
                   finalList,
                   filter.PageNumber,
                   filter.PageSize
                   );

            var responseObject = new ViewPagerDto<ViewPatientVisitsListWithDetailDto>
            {
                TotalCount = pagedList.TotalCount,
                PageSize = pagedList.PageSize,
                CurrentPage = pagedList.CurrentPage,
                TotalPages = pagedList.TotalPages,
                HasNext = pagedList.HasNext,
                HasPrevious = pagedList.HasPrevious,
                List = pagedList
            };

            return responseObject;

        }

        // All Patient Visit list which are discharged and SSC Claim Confirm
        public async Task<ViewPagerDto<ViewPatientVisitsListWithDetailDto>> GetSscClaimConfirmPatientVisitsListWithDetail(FilterPatientVisitDto filter)
        {
            List<string> user = new List<string>();
            if (filter.User != null)
                user = filter!.User!.Split(',').ToList();


            var finalList = _uowPatientOpenVisit.GetDbContext().ViewPatientOpenVisitLists.Where(x => x.IsDischarge == true && x.IsEligibleForSsc == true && x.IsSscClaimed != null)
                .WhereIf(!string.IsNullOrEmpty(filter.FullName), x => x.PatientName!.ToLower().StartsWith(filter.FullName!))
                .WhereIf(!string.IsNullOrEmpty(filter.TokenNo), x => x.TokenNo == filter.TokenNo!.PadLeft(4, '0'))
                .WhereIf(!string.IsNullOrEmpty(filter.Cnic), x => x.Cnic == filter.Cnic)
                .WhereIf(!string.IsNullOrEmpty(filter.MobileNo), x => x.PatientMobileNo!.ToLower().StartsWith(filter.MobileNo!))
                .WhereIf(!string.IsNullOrEmpty(filter.Mrno), x => x.MrNo!.ToLower().StartsWith(filter.Mrno!))
                .WhereIf(!string.IsNullOrEmpty(filter.User), x => user.Contains(x.CreatedById.ToString()!))
                .WhereIf(!AppCommonMethod.IsNullorZeroInt(filter.ProvinceId), x => x.ProvinceId == filter.ProvinceId)
                .WhereIf(!AppCommonMethod.IsNullorZeroInt(filter.DivisionId), x => x.DivisionId == filter.DivisionId)
                .WhereIf(!AppCommonMethod.IsNullorZeroInt(filter.DistrictId), x => x.DistrictId == filter.DistrictId)
                .WhereIf(!AppCommonMethod.IsNullorZeroInt(filter.TehsilId), x => x.TehsilId == filter.TehsilId)
                .WhereIf(!AppCommonMethod.IsNullorZeroInt(filter.DepartmentId), x => x.DepartementLookupId == filter.DepartmentId)
                .WhereIf(!AppCommonMethod.IsNullorZeroInt(filter.SectionId), x => x.SectionLookupId == filter.SectionId)
                .WhereIf(!AppCommonMethod.IsNullorZeroInt(filter.HealthFacilityId), x => x.HealthFacilityId == filter.HealthFacilityId)
                .WhereIf(!AppCommonMethod.IsNullorEmptyDate(filter.StartDate), x => x.CreatedOn!.Value.Date >= filter.StartDate!.Value.Date)
                .WhereIf(!AppCommonMethod.IsNullorEmptyDate(filter.EndDate), x => x.CreatedOn!.Value.Date < filter.EndDate!.Value.AddDays(1).Date)



                .OrderByDescending(x => x.CreatedOn)
                .Select(x =>
                new ViewPatientVisitsListWithDetailDto
                {
                    PatientVisitId = x.PatientVisitId,
                    PatientId = x.PatientId,
                    FullName = x.PatientName,
                    MobileNo = x.PatientMobileNo,
                    PatientProvinceId = x.PatientProvinceId,
                    Mrno = x.MrNo,
                    Cnic = x.Cnic,
                    VisitDate = x.VisitDate,
                    CreatedBy = x.CreatedBy!,
                    CreatedOn = x.CreatedOn,
                    UpdatedBy = x.UpdatedBy!,
                    UpdatedOn = x.UpdatedOn,
                    Department = x.Department,
                    Section = x.Section,
                    PatientDiagnoseId = x.PatientDiagnoseId,
                    FormType = x.FormType,
                    IsDischarge = x.IsDischarge,

                    IsSscClaimed = x.IsSscClaimed,
                    SscNotConfirmReason = x.SscNotConfirmReason,
                    SscClaimedDate = x.SscClaimedDate,

                    IsEligibleForSsc = x.IsEligibleForSsc,
                    SscNumber = x.SscNumber,
                    SscNotEligibleReason = x.SscNotEligibleReason
                });

            var pagedList = await PagedListDto<ViewPatientVisitsListWithDetailDto>.ToPagedListAsync(
                   finalList,
                   filter.PageNumber,
                   filter.PageSize
                   );

            var responseObject = new ViewPagerDto<ViewPatientVisitsListWithDetailDto>
            {
                TotalCount = pagedList.TotalCount,
                PageSize = pagedList.PageSize,
                CurrentPage = pagedList.CurrentPage,
                TotalPages = pagedList.TotalPages,
                HasNext = pagedList.HasNext,
                HasPrevious = pagedList.HasPrevious,
                List = pagedList
            };

            return responseObject;
            //return null;
        }

        #endregion

        #region Helper Methods

        private void FillEntity(PatientOpenVisit obj)
        {
            if (obj.PatientOpenVisitId == Guid.Empty)
            {
                obj.PatientOpenVisitId = Guid.NewGuid();
                obj.CreatedBy = _tokenService.GetUserId();
                obj.CreatedOn = DateTime.Now;
                obj.ActionTypeId = (int)ActionTypeEnum.Create;
            }
            else
            {
                obj.UpdatedBy = _tokenService.GetUserId();
                obj.UpdatedOn = DateTime.Now;
                obj.ActionTypeId = (int)ActionTypeEnum.Edit;
            }
        }
        private void FillEntityDelete(PatientOpenVisit obj)
        {
            if (obj != null)
            {
                obj.DeletedBy = _tokenService.GetUserId();
                obj.DeletedOn = DateTime.Now;
                obj.ActionTypeId = (int)ActionTypeEnum.Deleted;
            }
        }

        //private void FillEntityForDischargePatients(PatientOpenVisit obj)
        //{
        //    obj!.IsDischarge = true;
        //    obj.UpdatedBy = _tokenService.GetUserId();
        //    obj.UpdatedOn = DateTime.Now;
        //    obj.ActionTypeId = (int)ActionTypeEnum.Edit;
        //}

        #endregion
    }
}