using HMIS.Dashboard.Domain.Models.DbModels;
using HMIS.Dashboard.Domain.Models.DTO.MedicineDispatchDto;
using HMIS.Dashboard.Domain.Models.DTO.PatientAssessmentDto;
using HMIS.Dashboard.Domain.Models.DTO.PatientContactDetailsDTO;
using HMIS.Dashboard.Domain.Models.DTO.PatientDiagnoseDiseaseDto;
using HMIS.Dashboard.Domain.Models.DTO.PatientDiagnoseProcedureDto;
using HMIS.Dashboard.Domain.Models.DTO.PatientLabTestDto;
using HMIS.Dashboard.Domain.Models.DTO.PatientPrescriptionDto;
using HMIS.Dashboard.Domain.Models.DTO.PatientScreeningDto;
using HMIS.Dashboard.Domain.Models.DTO.PatientVaccinationDto;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace HMIS.Dashboard.Domain.Models.DTO.PatientDiagnoseDto
{
    public class CreateOrEditPatientDiagnoseWithPrescriptionDto
    {
        public CreateOrEditPatientDiagnoseWithPrescriptionDto()
        {
            PatientDiagnoseDiseases = new List<CreateOrEditPatientDiagnoseDiseaseDto>();

            PatientPrescriptions = new List<CreateOrEditPatientPrescriptionDto>();

            PatientLabTests = new List<CreateOrEditPatientLabTestDto>();

            PatientContactDetails = new List<CreatePatientContactDetailsDTO>();

            PatientDiagnoseProcedures = new List<CreateOrEditPatientDiagnoseProcedureDto>();
            PatientScreening = new CreateOrEditPatientScreeningDto();
            PatientAssessment = new CreateOrEditPatientAssessmentDto();
            PatientVaccination = new CreateOrEditPatientVaccinationDto();
            PatientScreeningTestKitsDispense = new CreateOrEditPatientMedicineDispatchDto();
        }
        public Guid? PatientDiagnoseId { get; set; }

        public Guid? PatientId { get; set; }

        public Guid? PatientVisitId { get; set; }
        public Guid? PatientStatusProfileId { get; set; }
        public string? DeseaseSubType { get; set; }
        public string? TbPatientConfirmationType { get; set; }
        public Guid? OutcomeStatusProfileId { get; set; }

        public string? PresentComplaints { get; set; }

        public string? Examination { get; set; }

        public string? PatientMedicalHistory { get; set; }

        public string? AdviseGiven { get; set; }

        public DateTime? FollowupDate { get; set; }
        public Guid? MedicineRegimeProfileId { get; set; }
        public Guid? PatientVisitTypeProfileId { get; set; }
        public int? PatientVisitCount { get; set; }

        public Guid? SvrStatusProfileId { get; set; }
        public Guid? PcrStatusProfileId { get; set; }
        public Guid? FollowupDateTypeProfileId { get; set; }

        public Guid? DiagnosedBy { get; set; }
        public Guid? Doctor { get; set; }
        public int? BedNo { get; set; }

        public bool IsMedicine { get; set; }

        public bool? IsMlc { get; set; }
        public bool IsLab { get; set; }
        public bool? IsSendToCdc { get; set; }
        public bool IsRefer { get; set; }
        public bool IsConfirmed { get; set; }
        public bool? IsMedicinePrescribedInLastVisit { get; set; }
        public string? ReactionNote { get; set; }
        public string FormType { get; set; }

        public int? ReferredHealthFacilityId { get; set; }
        public int? ReferDepartment { get; set; }
        public int? ReferSection { get; set; }

        public bool IsVisitClose { get; set; }

        public bool IsWillingToBuyMedPrivately { get; set; }
        public bool? IsDischargeDiagnose { get; set; }
        public bool? IsDiagnoseExternally { get; set; }
        public bool? IsAutoGenerated { get; set; }
        public bool? IsFromCallCenter { get; set; }
        public bool? IsPatientHistory { get; set; } = false;

        public Guid? SourceSystemId { get; set; }

        public string? SourceDoctorName { get; set; }

        public bool IsActive { get; set; }
        public bool IsVerifiedByConsultant { get; set; }
        public bool IsReferToDRTB { get; set; } = false;
        public string? DRTBCenter { get; set; } 
        public bool IsExpertTest { get; set; }
        public bool? IsFollowup { get; set; }
        public int? FollowupNo { get; set; }
        public string? FormData { get; set; }
        public virtual CreateOrEditPatientScreeningDto PatientScreening { get; set; }
        public virtual CreateOrEditPatientAssessmentDto PatientAssessment { get; set; }
        public virtual CreateOrEditPatientVaccinationDto PatientVaccination { get; set; }
        public virtual CreateOrEditPatientMedicineDispatchDto PatientScreeningTestKitsDispense { get; set; }

        public virtual ICollection<CreateOrEditPatientDiagnoseDiseaseDto> PatientDiagnoseDiseases { get; set; }
        
        public virtual ICollection<CreateOrEditPatientPrescriptionDto> PatientPrescriptions { get; set; }

        public virtual ICollection<CreateOrEditPatientLabTestDto> PatientLabTests { get; set; }

        public virtual ICollection<CreatePatientContactDetailsDTO> PatientContactDetails { get; set; }

        public virtual ICollection<CreateOrEditPatientDiagnoseProcedureDto> PatientDiagnoseProcedures { get; set; }

    }
}
